//This file is automatically generated

// api-credential-controller

import { ApiCredentialController } from '../controller';
export default {
    actions: {
        [ApiCredentialController.create.method] : {
            summary: '新增',
            method: 'post',
            url: (payload) => `/api/api-credentials`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'客户端调用推送服务凭证','$ref':'#/definitions/客户端调用推送服务凭证'}}],
        },
        [ApiCredentialController.deleteById.method] : {
            summary: '按主键删除',
            method: 'delete',
            url: (payload) => `/api/api-credentials/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [ApiCredentialController.deleteByIds.method] : {
            summary: '按主键集合删除',
            method: 'put',
            url: (payload) => `/api/api-credentials/bulk-delete`,
            parameters: [{'in':'body','name':'ids','description':'ids','required':true,'schema':{'type':'array','items':{'type':'string'}}}],
        },
        [ApiCredentialController.findByCriteria.method] : {
            summary: '按条件查询',
            method: 'get',
            url: (payload) => `/api/api-credentials/query`,
            parameters: [{'name':'apiKey','in':'query','required':false,'type':'string'},{'name':'appId','in':'query','required':false,'type':'string'},{'name':'clientCode','in':'query','required':false,'type':'string'},{'name':'credentialName','in':'query','required':false,'type':'string'},{'name':'id','in':'query','description':'id','required':false,'type':'string'},{'name':'includePortal','in':'query','required':false,'type':'boolean'},{'name':'tenantId','in':'query','description':'租户id','required':false,'type':'string'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'}],
        },
        [ApiCredentialController.findById.method] : {
            summary: '按主键查询',
            method: 'get',
            url: (payload) => `/api/api-credentials/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [ApiCredentialController.pageByCriteria.method] : {
            summary: '按条件分页查询',
            method: 'get',
            url: (payload) => `/api/api-credentials/page-query`,
            parameters: [{'name':'apiKey','in':'query','required':false,'type':'string'},{'name':'appId','in':'query','required':false,'type':'string'},{'name':'clientCode','in':'query','required':false,'type':'string'},{'name':'credentialName','in':'query','required':false,'type':'string'},{'name':'id','in':'query','description':'id','required':false,'type':'string'},{'name':'includePortal','in':'query','required':false,'type':'boolean'},{'name':'pageNum','in':'query','description':'第几页，从0开始','required':true,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','description':'单页条数','required':true,'type':'integer','format':'int32'},{'name':'tenantId','in':'query','description':'租户id','required':false,'type':'string'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'}],
        },
        [ApiCredentialController.refreshApiKey.method] : {
            summary: '刷新apiKey',
            method: 'put',
            url: (payload) => `/api/api-credentials/${payload.id}/api-key`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [ApiCredentialController.update.method] : {
            summary: '更新',
            method: 'put',
            url: (payload) => `/api/api-credentials`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'客户端调用推送服务凭证','$ref':'#/definitions/客户端调用推送服务凭证'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
