//This file is automatically generated

// app-archive-controller

import { AppArchiveController } from '../controller';
export default {
    actions: {
        [AppArchiveController.create.method] : {
            summary: '新增',
            method: 'post',
            url: (payload) => `/api/app-archives`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'应用包','$ref':'#/definitions/应用包'}}],
        },
        [AppArchiveController.deleteById.method] : {
            summary: '按主键删除',
            method: 'delete',
            url: (payload) => `/api/app-archives/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [AppArchiveController.deleteByIds.method] : {
            summary: '按主键集合删除',
            method: 'put',
            url: (payload) => `/api/app-archives/bulk-delete`,
            parameters: [{'in':'body','name':'ids','description':'ids','required':true,'schema':{'type':'array','items':{'type':'string'}}}],
        },
        [AppArchiveController.findByCriteria.method] : {
            summary: '按条件查询',
            method: 'get',
            url: (payload) => `/api/app-archives/query`,
            parameters: [{'name':'appId','in':'query','required':false,'type':'string'},{'name':'build','in':'query','required':false,'type':'string'},{'name':'bundleId','in':'query','required':false,'type':'string'},{'name':'id','in':'query','description':'id','required':false,'type':'string'},{'name':'loadDownloadCount','in':'query','required':false,'type':'boolean'},{'name':'packageName','in':'query','required':false,'type':'string'},{'name':'platform','in':'query','required':false,'type':'string','enum':['IOS','ANDROID']},{'name':'status','in':'query','required':false,'type':'string','enum':['CREATED','GRAYSCALE','ONLINE','OFFLINE']},{'name':'tenantId','in':'query','description':'租户id','required':false,'type':'string'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'},{'name':'version','in':'query','required':false,'type':'string'}],
        },
        [AppArchiveController.findById.method] : {
            summary: '按主键查询',
            method: 'get',
            url: (payload) => `/api/app-archives/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [AppArchiveController.handleWhitelist.method] : {
            summary: '授权',
            method: 'put',
            url: (payload) => `/api/app-archives/${payload.id}/whitelist`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'},{'in':'body','name':'operatableAuths','description':'operatableAuths','required':true,'schema':{'type':'array','items':{'originalRef':'操作授权','$ref':'#/definitions/操作授权'}}}],
        },
        [AppArchiveController.loadWhitelist.method] : {
            summary: '获取授权',
            method: 'get',
            url: (payload) => `/api/app-archives/${payload.id}/whitelist`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [AppArchiveController.pageByCriteria.method] : {
            summary: '按条件分页查询',
            method: 'get',
            url: (payload) => `/api/app-archives/page-query`,
            parameters: [{'name':'appId','in':'query','required':false,'type':'string'},{'name':'build','in':'query','required':false,'type':'string'},{'name':'bundleId','in':'query','required':false,'type':'string'},{'name':'id','in':'query','description':'id','required':false,'type':'string'},{'name':'loadDownloadCount','in':'query','required':false,'type':'boolean'},{'name':'packageName','in':'query','required':false,'type':'string'},{'name':'pageNum','in':'query','description':'第几页，从0开始','required':true,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','description':'单页条数','required':true,'type':'integer','format':'int32'},{'name':'platform','in':'query','required':false,'type':'string','enum':['IOS','ANDROID']},{'name':'status','in':'query','required':false,'type':'string','enum':['CREATED','GRAYSCALE','ONLINE','OFFLINE']},{'name':'tenantId','in':'query','description':'租户id','required':false,'type':'string'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'},{'name':'version','in':'query','required':false,'type':'string'}],
        },
        [AppArchiveController.update.method] : {
            summary: '更新',
            method: 'put',
            url: (payload) => `/api/app-archives`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'应用包','$ref':'#/definitions/应用包'}}],
        },
        [AppArchiveController.uploadArchive.method] : {
            summary: 'app介质上传',
            method: 'post',
            url: (payload) => `/api/app-archives/upload/archive`,
            parameters: [{'name':'archive','in':'formData','description':'archive','required':true,'type':'file'}],
        },
        [AppArchiveController.uploadPreviews.method] : {
            summary: '上传预览图',
            method: 'post',
            url: (payload) => `/api/app-archives/upload/previews`,
            parameters: [{'name':'previews','in':'formData','description':'previews','required':true,'type':'array','items':{'type':'file'},'collectionFormat':'multi'}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
