//This file is automatically generated

// appstore-api-controller

import { AppstoreApiController } from '../controller';
export default {
    actions: {
        [AppstoreApiController.uploadAppArchive.method] : {
            summary: '应用上传',
            method: 'post',
            url: (payload) => `/xapi/app-archives/upload`,
            parameters: [{'in':'formData','name':'appId','description':'应用id','required':false,'schema':{'type':'string'}},{'in':'formData','name':'archive','description':'介质','required':false,'schema':{'type':'file'}},{'in':'formData','name':'changeLog','description':'[optional] 更新描述','required':false,'schema':{'type':'string'}},{'in':'formData','name':'description','description':'[optional] 版本描述','required':false,'schema':{'type':'string'}},{'in':'formData','name':'grayInstPsw','description':'[optional] 灰度下载密码','required':false,'schema':{'type':'string'}},{'in':'formData','name':'iosPlistUrl','description':'[optional] ios plist地址, 上传包为ios的时候可选, 为空则为系统默认生成地址','required':false,'schema':{'type':'string'}},{'in':'formData','name':'updateMode','description':'[optional] 更新模式','required':false,'schema':{'type':'string'}},{'in':'formData','name':'whitelist[0].authId','required':false,'schema':{'type':'string'}},{'in':'formData','name':'whitelist[0].authType','required':false,'schema':{'type':'string'}}],
        },
        [AppstoreApiController.uploadMicroappArchive.method] : {
            summary: '微应用上传',
            method: 'post',
            url: (payload) => `/xapi/microapp-archives/upload`,
            parameters: [{'in':'formData','name':'appId','description':'应用id','required':false,'schema':{'type':'string'}},{'in':'formData','name':'archive','description':'介质','required':false,'schema':{'type':'file'}},{'in':'formData','name':'changeLog','description':'[optional] 更新描述','required':false,'schema':{'type':'string'}},{'in':'formData','name':'description','description':'[optional] 版本描述','required':false,'schema':{'type':'string'}},{'in':'formData','name':'microappType','description':'微应用类型','required':false,'schema':{'type':'string'}},{'in':'formData','name':'updateMode','description':'[optional] 更新模式','required':false,'schema':{'type':'string'}},{'in':'formData','name':'whitelist[0].authId','required':false,'schema':{'type':'string'}},{'in':'formData','name':'whitelist[0].authType','required':false,'schema':{'type':'string'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
