//This file is automatically generated

// archive-download-stat-controller

import { ArchiveDownloadStatController } from '../controller';
export default {
    actions: {
        [ArchiveDownloadStatController.getAppTodyDownloadCount.method] : {
            summary: '查询应用当天下载次数',
            method: 'get',
            url: (payload) => `/api/download-stats/app/${payload.appId}/today`,
            parameters: [{'name':'appId','in':'path','description':'appId','required':true,'type':'string'}],
        },
        [ArchiveDownloadStatController.getAppTotalDownloadCount.method] : {
            summary: '查询应用总下载次数',
            method: 'get',
            url: (payload) => `/api/download-stats/app/${payload.appId}/total`,
            parameters: [{'name':'appId','in':'path','description':'appId','required':true,'type':'string'}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
