//This file is automatically generated

// auth-tpl-controller

import { AuthTplController } from '../controller';
export default {
    actions: {
        [AuthTplController.addRootResourceGroups.method] : {
            summary: '为权限模板添加根资源组',
            method: 'put',
            url: (payload) => `/api/auth-templates/${payload.id}/resource-grooups/${payload.resGroupId}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'},{'name':'resGroupId','in':'path','description':'resGroupId','required':true,'type':'string'}],
        },
        [AuthTplController.create.method] : {
            summary: '新增',
            method: 'post',
            url: (payload) => `/api/auth-templates`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'AuthTpl','$ref':'#/definitions/AuthTpl'}}],
        },
        [AuthTplController.deleteByIds.method] : {
            summary: '按主键集合删除',
            method: 'put',
            url: (payload) => `/api/auth-templates/bulk-delete`,
            parameters: [{'in':'body','name':'ids','description':'ids','required':true,'schema':{'type':'array','items':{'type':'string'}}}],
        },
        [AuthTplController.findById.method] : {
            summary: '按主键查询',
            method: 'get',
            url: (payload) => `/api/auth-templates/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [AuthTplController.queryALLAuthTpls.method] : {
            summary: '列出所有的权限模板',
            method: 'get',
            url: (payload) => `/api/auth-templates/search`,
            parameters: [{'name':'id','in':'query','description':'Id','required':false,'type':'string'},{'name':'name','in':'query','description':'名称','required':false,'type':'string'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'}],
        },
        [AuthTplController.queryResGroups.method] : {
            summary: '查询某个权限模板下的根资源组',
            method: 'get',
            url: (payload) => `/api/auth-templates/${payload.id}/resource-grooups`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'},{'name':'showAllRootResGroups','in':'query','description':'showAllRootResGroups','required':false,'type':'boolean','default':false}],
        },
        [AuthTplController.querySubRoleTemplates.method] : {
            summary: '查询权限模板下的角色模板',
            method: 'get',
            url: (payload) => `/api/auth-templates/${payload.id}/role-templates`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'},{'name':'roleTemplateName','in':'query','description':'roleTemplateName','required':false,'type':'string'}],
        },
        [AuthTplController.removeRootResourceGroups.method] : {
            summary: '从权限模板中移除根资源组',
            method: 'delete',
            url: (payload) => `/api/auth-templates/${payload.id}/resource-grooups/${payload.resGroupId}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'},{'name':'resGroupId','in':'path','description':'resGroupId','required':true,'type':'string'}],
        },
        [AuthTplController.update.method] : {
            summary: '更新',
            method: 'put',
            url: (payload) => `/api/auth-templates`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'AuthTpl','$ref':'#/definitions/AuthTpl'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
