//This file is automatically generated

// business-excel-controller

import { BusinessExcelController } from '../controller';
export default {
    actions: {
        [BusinessExcelController.exportExcel.method] : {
            summary: '导出通讯录',
            method: 'get',
            url: (payload) => `/api/excel`,
            parameters: [],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
