//This file is automatically generated

// business-inform-resource-controller

import { BusinessInformResourceController } from '../controller';
export default {
    actions: {
        [BusinessInformResourceController.batchCreate.method] : {
            summary: '批量增加',
            method: 'post',
            url: (payload) => `/api/business-inform-resources/bulk-create`,
            parameters: [{'in':'body','name':'informResources','description':'informResources','required':true,'schema':{'type':'array','items':{'originalRef':'资讯楼层对象','$ref':'#/definitions/资讯楼层对象'}}}],
        },
        [BusinessInformResourceController.batchUpdate.method] : {
            summary: '批量更新',
            method: 'put',
            url: (payload) => `/api/business-inform-resources/bulk-update`,
            parameters: [{'in':'body','name':'informResources','description':'informResources','required':true,'schema':{'type':'array','items':{'originalRef':'资讯楼层对象','$ref':'#/definitions/资讯楼层对象'}}}],
        },
        [BusinessInformResourceController.create.method] : {
            summary: '新增',
            method: 'post',
            url: (payload) => `/api/business-inform-resources`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'资讯楼层对象','$ref':'#/definitions/资讯楼层对象'}}],
        },
        [BusinessInformResourceController.deleteById.method] : {
            summary: '按主键删除',
            method: 'delete',
            url: (payload) => `/api/business-inform-resources/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [BusinessInformResourceController.deleteByIds.method] : {
            summary: '按主键集合删除',
            method: 'put',
            url: (payload) => `/api/business-inform-resources/bulk-delete`,
            parameters: [{'in':'body','name':'ids','description':'ids','required':true,'schema':{'type':'array','items':{'type':'string'}}}],
        },
        [BusinessInformResourceController.findByCriteria.method] : {
            summary: '按条件分页查询',
            method: 'get',
            url: (payload) => `/api/business-inform-resources/page-query`,
            parameters: [{'name':'floorId','in':'query','description':'楼层id','required':false,'type':'string'},{'name':'id','in':'query','description':'id','required':false,'type':'string'},{'name':'informResourceName','in':'query','description':'资源名','required':false,'type':'string'},{'name':'informTheme','in':'query','description':'资讯主题','required':false,'type':'string'},{'name':'pageNum','in':'query','description':'第几页，从0开始','required':true,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','description':'单页条数','required':true,'type':'integer','format':'int32'},{'name':'tenantId','in':'query','description':'租户id','required':false,'type':'string'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'}],
        },
        [BusinessInformResourceController.findById.method] : {
            summary: '按主键查询',
            method: 'get',
            url: (payload) => `/api/business-inform-resources/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [BusinessInformResourceController.update.method] : {
            summary: '更新',
            method: 'put',
            url: (payload) => `/api/business-inform-resources`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'资讯楼层对象','$ref':'#/definitions/资讯楼层对象'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
