//This file is automatically generated

// business-common-controller

import { BusinessCommonController } from '../controller';
export default {
    actions: {
        [BusinessCommonController.uploadImg.method] : {
            summary: '图片上传',
            method: 'post',
            url: (payload) => `/api/common/upload`,
            parameters: [{'name':'file','in':'formData','description':'file','required':true,'type':'file'}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
