//This file is automatically generated

// business-scheme-conf-controller

import { BusinessSchemeConfController } from '../controller';
export default {
    actions: {
        [BusinessSchemeConfController.create.method] : {
            summary: '新增',
            method: 'post',
            url: (payload) => `/api/business-scheme-confs`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'方案配置对象','$ref':'#/definitions/方案配置对象'}}],
        },
        [BusinessSchemeConfController.createWithWhiteList.method] : {
            summary: '新增(携带分享和截屏白名单)',
            method: 'post',
            url: (payload) => `/api/business-scheme-confs/white-list`,
            parameters: [{'in':'body','name':'schemeConfDTO2','description':'schemeConfDTO2','required':true,'schema':{'originalRef':'管理端新增，修改传参','$ref':'#/definitions/管理端新增，修改传参'}}],
        },
        [BusinessSchemeConfController.deleteById.method] : {
            summary: '按主键删除',
            method: 'delete',
            url: (payload) => `/api/business-scheme-confs/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [BusinessSchemeConfController.deleteByIds.method] : {
            summary: '按主键集合删除',
            method: 'put',
            url: (payload) => `/api/business-scheme-confs/bulk-delete`,
            parameters: [{'in':'body','name':'ids','description':'ids','required':true,'schema':{'type':'array','items':{'type':'string'}}}],
        },
        [BusinessSchemeConfController.findById.method] : {
            summary: '按主键查询',
            method: 'get',
            url: (payload) => `/api/business-scheme-confs/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [BusinessSchemeConfController.findByIdWithWhiteList.method] : {
            summary: '根据id查询(携带分享和截屏白名单)',
            method: 'get',
            url: (payload) => `/api/business-scheme-confs/white-list/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [BusinessSchemeConfController.update.method] : {
            summary: '更新',
            method: 'put',
            url: (payload) => `/api/business-scheme-confs`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'方案配置对象','$ref':'#/definitions/方案配置对象'}}],
        },
        [BusinessSchemeConfController.updateWithWhiteList.method] : {
            summary: '更新(携带分享和截屏白名单)',
            method: 'put',
            url: (payload) => `/api/business-scheme-confs/white-list`,
            parameters: [{'in':'body','name':'schemeConfDTO2','description':'schemeConfDTO2','required':true,'schema':{'originalRef':'管理端新增，修改传参','$ref':'#/definitions/管理端新增，修改传参'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
