//This file is automatically generated

// business-dict-controller

import { BusinessDictController } from '../controller';
export default {
    actions: {
        [BusinessDictController.create.method] : {
            summary: '新增',
            method: 'post',
            url: (payload) => `/api/business-dicts`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'数据字典对象','$ref':'#/definitions/数据字典对象'}}],
        },
        [BusinessDictController.deleteById.method] : {
            summary: '按主键删除',
            method: 'delete',
            url: (payload) => `/api/business-dicts/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [BusinessDictController.deleteByIds.method] : {
            summary: '按主键集合删除',
            method: 'put',
            url: (payload) => `/api/business-dicts/bulk-delete`,
            parameters: [{'in':'body','name':'ids','description':'ids','required':true,'schema':{'type':'array','items':{'type':'string'}}}],
        },
        [BusinessDictController.findById.method] : {
            summary: '按主键查询',
            method: 'get',
            url: (payload) => `/api/business-dicts/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [BusinessDictController.update.method] : {
            summary: '更新',
            method: 'put',
            url: (payload) => `/api/business-dicts`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'数据字典对象','$ref':'#/definitions/数据字典对象'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
