//This file is automatically generated

// business-banner-resource-controller

import { BusinessBannerResourceController } from '../controller';
export default {
    actions: {
        [BusinessBannerResourceController.batchCreate.method] : {
            summary: '批量增加',
            method: 'post',
            url: (payload) => `/api/business-banner-resources/bulk-create`,
            parameters: [{'in':'body','name':'bannerResources','description':'bannerResources','required':true,'schema':{'type':'array','items':{'originalRef':'banner楼层对象','$ref':'#/definitions/banner楼层对象'}}}],
        },
        [BusinessBannerResourceController.batchUpdate.method] : {
            summary: '批量更新',
            method: 'put',
            url: (payload) => `/api/business-banner-resources/bulk-update`,
            parameters: [{'in':'body','name':'bannerResources','description':'bannerResources','required':true,'schema':{'type':'array','items':{'originalRef':'banner楼层对象','$ref':'#/definitions/banner楼层对象'}}}],
        },
        [BusinessBannerResourceController.create.method] : {
            summary: '新增',
            method: 'post',
            url: (payload) => `/api/business-banner-resources`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'banner楼层对象','$ref':'#/definitions/banner楼层对象'}}],
        },
        [BusinessBannerResourceController.deleteById.method] : {
            summary: '按主键删除',
            method: 'delete',
            url: (payload) => `/api/business-banner-resources/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [BusinessBannerResourceController.deleteByIds.method] : {
            summary: '按主键集合删除',
            method: 'put',
            url: (payload) => `/api/business-banner-resources/bulk-delete`,
            parameters: [{'in':'body','name':'ids','description':'ids','required':true,'schema':{'type':'array','items':{'type':'string'}}}],
        },
        [BusinessBannerResourceController.findByCriteria.method] : {
            summary: '按条件分页查询',
            method: 'get',
            url: (payload) => `/api/business-banner-resources/page-query`,
            parameters: [{'name':'bannerResourceName','in':'query','description':'资源名','required':false,'type':'string'},{'name':'floorId','in':'query','description':'楼层id','required':false,'type':'string'},{'name':'id','in':'query','description':'id','required':false,'type':'string'},{'name':'pageNum','in':'query','description':'第几页，从0开始','required':true,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','description':'单页条数','required':true,'type':'integer','format':'int32'},{'name':'tenantId','in':'query','description':'租户id','required':false,'type':'string'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'}],
        },
        [BusinessBannerResourceController.findById.method] : {
            summary: '按主键查询',
            method: 'get',
            url: (payload) => `/api/business-banner-resources/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [BusinessBannerResourceController.update.method] : {
            summary: '更新',
            method: 'put',
            url: (payload) => `/api/business-banner-resources`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'banner楼层对象','$ref':'#/definitions/banner楼层对象'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
