//This file is automatically generated

// business-custom-floor-conf-controller

import { BusinessCustomFloorConfController } from '../controller';
export default {
    actions: {
        [BusinessCustomFloorConfController.create.method] : {
            summary: '新增',
            method: 'post',
            url: (payload) => `/api/business-custom-floor-configs`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'自定义楼层配置','$ref':'#/definitions/自定义楼层配置'}}],
        },
        [BusinessCustomFloorConfController.deleteById.method] : {
            summary: '按主键删除',
            method: 'delete',
            url: (payload) => `/api/business-custom-floor-configs/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [BusinessCustomFloorConfController.deleteByIds.method] : {
            summary: '按主键集合删除',
            method: 'put',
            url: (payload) => `/api/business-custom-floor-configs/bulk-delete`,
            parameters: [{'in':'body','name':'ids','description':'ids','required':true,'schema':{'type':'array','items':{'type':'string'}}}],
        },
        [BusinessCustomFloorConfController.findByCriteria.method] : {
            summary: '按条件分页查询',
            method: 'get',
            url: (payload) => `/api/business-custom-floor-configs/page-query`,
            parameters: [{'name':'id','in':'query','description':'id','required':false,'type':'string'},{'name':'pageNum','in':'query','description':'第几页，从0开始','required':true,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','description':'单页条数','required':true,'type':'integer','format':'int32'},{'name':'pageTabId','in':'query','description':'tab页id，该页面从属于tab页','required':false,'type':'string'},{'name':'tenantId','in':'query','description':'租户id','required':false,'type':'string'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'}],
        },
        [BusinessCustomFloorConfController.findById.method] : {
            summary: '按主键查询',
            method: 'get',
            url: (payload) => `/api/business-custom-floor-configs/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [BusinessCustomFloorConfController.update.method] : {
            summary: '更新',
            method: 'put',
            url: (payload) => `/api/business-custom-floor-configs`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'自定义楼层配置','$ref':'#/definitions/自定义楼层配置'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
