//This file is automatically generated

// business-tab-page-controller

import { BusinessTabPageController } from '../controller';
export default {
    actions: {
        [BusinessTabPageController.create.method] : {
            summary: '新增',
            method: 'post',
            url: (payload) => `/api/business-tab-pages`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'tab页对象','$ref':'#/definitions/tab页对象'}}],
        },
        [BusinessTabPageController.deleteById.method] : {
            summary: '按主键删除',
            method: 'delete',
            url: (payload) => `/api/business-tab-pages/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [BusinessTabPageController.deleteByIds.method] : {
            summary: '按主键集合删除',
            method: 'put',
            url: (payload) => `/api/business-tab-pages/bulk-delete`,
            parameters: [{'in':'body','name':'ids','description':'ids','required':true,'schema':{'type':'array','items':{'type':'string'}}}],
        },
        [BusinessTabPageController.findByAppPageId.method] : {
            summary: '根据页面id获取tab页配置',
            method: 'get',
            url: (payload) => `/api/business-tab-pages/appPageId/${payload.appPageId}`,
            parameters: [{'name':'appPageId','in':'path','description':'appPageId','required':true,'type':'string'}],
        },
        [BusinessTabPageController.findById.method] : {
            summary: '按主键查询',
            method: 'get',
            url: (payload) => `/api/business-tab-pages/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [BusinessTabPageController.update.method] : {
            summary: '更新',
            method: 'put',
            url: (payload) => `/api/business-tab-pages`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'tab页对象','$ref':'#/definitions/tab页对象'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
