//This file is automatically generated

// business-auth-res-controller

import { BusinessAuthResController } from '../controller';
export default {
    actions: {
        [BusinessAuthResController.create.method] : {
            summary: '新增',
            method: 'post',
            url: (payload) => `/api/business-authRes`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'授权资源对象','$ref':'#/definitions/授权资源对象'}}],
        },
        [BusinessAuthResController.deleteById.method] : {
            summary: '按主键删除',
            method: 'delete',
            url: (payload) => `/api/business-authRes/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [BusinessAuthResController.deleteByIds.method] : {
            summary: '按主键集合删除',
            method: 'put',
            url: (payload) => `/api/business-authRes/bulk-delete`,
            parameters: [{'in':'body','name':'ids','description':'ids','required':true,'schema':{'type':'array','items':{'type':'string'}}}],
        },
        [BusinessAuthResController.findAuthBySchemeId.method] : {
            summary: '方案授权查询',
            method: 'get',
            url: (payload) => `/api/business-authRes/scheme`,
            parameters: [{'name':'authId','in':'query','required':false,'type':'string'},{'name':'authType','in':'query','required':false,'type':'string'},{'name':'resId','in':'query','required':false,'type':'string'},{'name':'resType','in':'query','required':false,'type':'string'},{'name':'type','in':'query','required':false,'type':'string'}],
        },
        [BusinessAuthResController.findById.method] : {
            summary: '按主键查询',
            method: 'get',
            url: (payload) => `/api/business-authRes/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [BusinessAuthResController.setAuthScheme.method] : {
            summary: '方案授权',
            method: 'post',
            url: (payload) => `/api/business-authRes/scheme/${payload.schemeId}`,
            parameters: [{'in':'body','name':'auth','description':'auth','required':true,'schema':{'originalRef':'方案授权','$ref':'#/definitions/方案授权'}},{'name':'schemeId','in':'path','description':'schemeId','required':true,'type':'string'}],
        },
        [BusinessAuthResController.update.method] : {
            summary: '更新',
            method: 'put',
            url: (payload) => `/api/business-authRes`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'授权资源对象','$ref':'#/definitions/授权资源对象'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
