//This file is automatically generated

// business-popup-page-controller

import { BusinessPopupPageController } from '../controller';
export default {
    actions: {
        [BusinessPopupPageController.create.method] : {
            summary: '新增',
            method: 'post',
            url: (payload) => `/api/business-popup-pages`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'弹出框页面对象','$ref':'#/definitions/弹出框页面对象'}}],
        },
        [BusinessPopupPageController.deleteById.method] : {
            summary: '按主键删除',
            method: 'delete',
            url: (payload) => `/api/business-popup-pages/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [BusinessPopupPageController.deleteByIds.method] : {
            summary: '按主键集合删除',
            method: 'put',
            url: (payload) => `/api/business-popup-pages/bulk-delete`,
            parameters: [{'in':'body','name':'ids','description':'ids','required':true,'schema':{'type':'array','items':{'type':'string'}}}],
        },
        [BusinessPopupPageController.findByAppPageId.method] : {
            summary: '根据页面id获取弹出框页面配置',
            method: 'get',
            url: (payload) => `/api/business-popup-pages/appPageId/${payload.appPageId}`,
            parameters: [{'name':'appPageId','in':'path','description':'appPageId','required':true,'type':'string'}],
        },
        [BusinessPopupPageController.findById.method] : {
            summary: '按主键查询',
            method: 'get',
            url: (payload) => `/api/business-popup-pages/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [BusinessPopupPageController.update.method] : {
            summary: '更新',
            method: 'put',
            url: (payload) => `/api/business-popup-pages`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'弹出框页面对象','$ref':'#/definitions/弹出框页面对象'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
