//This file is automatically generated

// business-scheme-controller

import { BusinessSchemeController } from '../controller';
export default {
    actions: {
        [BusinessSchemeController.create.method] : {
            summary: '新增',
            method: 'post',
            url: (payload) => `/api/business-schemes`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'方案对象','$ref':'#/definitions/方案对象'}}],
        },
        [BusinessSchemeController.deleteById.method] : {
            summary: '按主键删除',
            method: 'delete',
            url: (payload) => `/api/business-schemes/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [BusinessSchemeController.deleteByIds.method] : {
            summary: '按主键集合删除',
            method: 'put',
            url: (payload) => `/api/business-schemes/bulk-delete`,
            parameters: [{'in':'body','name':'ids','description':'ids','required':true,'schema':{'type':'array','items':{'type':'string'}}}],
        },
        [BusinessSchemeController.findByCriteria.method] : {
            summary: '按条件分页查询',
            method: 'get',
            url: (payload) => `/api/business-schemes/page-query`,
            parameters: [{'name':'appId','in':'query','description':'应用id','required':false,'type':'string'},{'name':'id','in':'query','description':'id','required':false,'type':'string'},{'name':'pageNum','in':'query','description':'第几页，从0开始','required':true,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','description':'单页条数','required':true,'type':'integer','format':'int32'},{'name':'schemeName','in':'query','description':'方案名','required':false,'type':'string'},{'name':'tenantId','in':'query','description':'租户id','required':false,'type':'string'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'}],
        },
        [BusinessSchemeController.findById.method] : {
            summary: '按主键查询',
            method: 'get',
            url: (payload) => `/api/business-schemes/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [BusinessSchemeController.update.method] : {
            summary: '更新',
            method: 'put',
            url: (payload) => `/api/business-schemes`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'方案对象','$ref':'#/definitions/方案对象'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
