//This file is automatically generated

// business-address-controller

import { BusinessAddressController } from '../controller';
export default {
    actions: {
        [BusinessAddressController.create.method] : {
            summary: '新增',
            method: 'post',
            url: (payload) => `/api/business-addresses`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'通讯录对象','$ref':'#/definitions/通讯录对象'}}],
        },
        [BusinessAddressController.deleteById.method] : {
            summary: '按主键删除',
            method: 'delete',
            url: (payload) => `/api/business-addresses/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [BusinessAddressController.deleteByIds.method] : {
            summary: '按主键集合删除',
            method: 'put',
            url: (payload) => `/api/business-addresses/bulk-delete`,
            parameters: [{'in':'body','name':'ids','description':'ids','required':true,'schema':{'type':'array','items':{'type':'string'}}}],
        },
        [BusinessAddressController.findById.method] : {
            summary: '按主键查询',
            method: 'get',
            url: (payload) => `/api/business-addresses/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [BusinessAddressController.findByPageId.method] : {
            summary: '根据页面id查询通讯录配置',
            method: 'get',
            url: (payload) => `/api/business-addresses/appPageId/${payload.appPageId}`,
            parameters: [{'name':'appPageId','in':'path','description':'appPageId','required':true,'type':'string'}],
        },
        [BusinessAddressController.update.method] : {
            summary: '更新',
            method: 'put',
            url: (payload) => `/api/business-addresses`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'通讯录对象','$ref':'#/definitions/通讯录对象'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
