//This file is automatically generated

// business-floor-controller

import { BusinessFloorController } from '../controller';
export default {
    actions: {
        [BusinessFloorController.batchUpdate.method] : {
            summary: '批量更新',
            method: 'put',
            url: (payload) => `/api/business-floors/bulk-update`,
            parameters: [{'in':'body','name':'floors','description':'floors','required':true,'schema':{'type':'array','items':{'originalRef':'楼层对象','$ref':'#/definitions/楼层对象'}}}],
        },
        [BusinessFloorController.create.method] : {
            summary: '新增',
            method: 'post',
            url: (payload) => `/api/business-floors`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'楼层对象','$ref':'#/definitions/楼层对象'}}],
        },
        [BusinessFloorController.deleteById.method] : {
            summary: '按主键删除',
            method: 'delete',
            url: (payload) => `/api/business-floors/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [BusinessFloorController.deleteByIds.method] : {
            summary: '按主键集合删除',
            method: 'put',
            url: (payload) => `/api/business-floors/bulk-delete`,
            parameters: [{'in':'body','name':'ids','description':'ids','required':true,'schema':{'type':'array','items':{'type':'string'}}}],
        },
        [BusinessFloorController.findByCriteria.method] : {
            summary: '按条件分页查询',
            method: 'get',
            url: (payload) => `/api/business-floors/page-query`,
            parameters: [{'name':'id','in':'query','description':'id','required':false,'type':'string'},{'name':'pageNum','in':'query','description':'第几页，从0开始','required':true,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','description':'单页条数','required':true,'type':'integer','format':'int32'},{'name':'pageTabId','in':'query','description':'tab页id，该页面从属于tab页','required':false,'type':'string'},{'name':'tenantId','in':'query','description':'租户id','required':false,'type':'string'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'}],
        },
        [BusinessFloorController.findById.method] : {
            summary: '按主键查询',
            method: 'get',
            url: (payload) => `/api/business-floors/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [BusinessFloorController.findByPageTabId.method] : {
            summary: '根据页面Id获取楼层列表',
            method: 'get',
            url: (payload) => `/api/business-floors/tabPageId/${payload.tabPageId}`,
            parameters: [{'name':'tabPageId','in':'path','description':'tabPageId','required':true,'type':'string'}],
        },
        [BusinessFloorController.update.method] : {
            summary: '更新',
            method: 'put',
            url: (payload) => `/api/business-floors`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'楼层对象','$ref':'#/definitions/楼层对象'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
