//This file is automatically generated

// business-app-page-controller

import { BusinessAppPageController } from '../controller';
export default {
    actions: {
        [BusinessAppPageController.create.method] : {
            summary: '新增',
            method: 'post',
            url: (payload) => `/api/business-app-pages`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'页面对象','$ref':'#/definitions/页面对象'}}],
        },
        [BusinessAppPageController.deleteById.method] : {
            summary: '按主键删除',
            method: 'delete',
            url: (payload) => `/api/business-app-pages/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [BusinessAppPageController.deleteByIds.method] : {
            summary: '按主键集合删除',
            method: 'put',
            url: (payload) => `/api/business-app-pages/bulk-delete`,
            parameters: [{'in':'body','name':'ids','description':'ids','required':true,'schema':{'type':'array','items':{'type':'string'}}}],
        },
        [BusinessAppPageController.findByCriteria.method] : {
            summary: '按条件分页查询',
            method: 'get',
            url: (payload) => `/api/business-app-pages/page-query`,
            parameters: [{'name':'id','in':'query','description':'id','required':false,'type':'string'},{'name':'pageName','in':'query','description':'页面名','required':false,'type':'string'},{'name':'pageNum','in':'query','description':'第几页，从0开始','required':true,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','description':'单页条数','required':true,'type':'integer','format':'int32'},{'name':'pageType','in':'query','description':'页面类型','required':false,'type':'string'},{'name':'schemeConfId','in':'query','description':'方案配置id','required':false,'type':'string'},{'name':'tenantId','in':'query','description':'租户id','required':false,'type':'string'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'}],
        },
        [BusinessAppPageController.findById.method] : {
            summary: '按主键查询',
            method: 'get',
            url: (payload) => `/api/business-app-pages/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [BusinessAppPageController.update.method] : {
            summary: '更新',
            method: 'put',
            url: (payload) => `/api/business-app-pages`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'页面对象','$ref':'#/definitions/页面对象'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
