//This file is automatically generated

// cof-tools-controller

import { CofToolsController } from '../controller';
export default {
    actions: {
        [CofToolsController.scanFunctions.method] : {
            summary: 'scanFunctions',
            method: 'get',
            url: (payload) => `/cof-tools/scan-functions`,
            parameters: [{'name':'basePackage','in':'query','description':'basePackage','required':false,'type':'string'}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
