//This file is automatically generated

// comment-controller

import { CommentController } from '../controller';
export default {
    actions: {
        [CommentController.create.method] : {
            summary: '新增',
            method: 'post',
            url: (payload) => `/api/comments`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'意见反馈','$ref':'#/definitions/意见反馈'}}],
        },
        [CommentController.deleteById.method] : {
            summary: '按主键删除',
            method: 'delete',
            url: (payload) => `/api/comments/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [CommentController.deleteByIds.method] : {
            summary: '按主键集合删除',
            method: 'put',
            url: (payload) => `/api/comments/bulk-delete`,
            parameters: [{'in':'body','name':'ids','description':'ids','required':true,'schema':{'type':'array','items':{'type':'string'}}}],
        },
        [CommentController.findByCriteria.method] : {
            summary: '按条件查询',
            method: 'get',
            url: (payload) => `/api/comments/query`,
            parameters: [{'name':'commentOn','in':'query','required':false,'type':'string'},{'name':'status','in':'query','required':false,'type':'string','enum':['TODO','DONE','REJECT']}],
        },
        [CommentController.findById.method] : {
            summary: '按主键查询',
            method: 'get',
            url: (payload) => `/api/comments/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [CommentController.pageByCriteria.method] : {
            summary: '按条件分页查询',
            method: 'get',
            url: (payload) => `/api/comments/page-query`,
            parameters: [{'name':'commentOn','in':'query','required':false,'type':'string'},{'name':'pageNum','in':'query','description':'第几页，从0开始','required':true,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','description':'单页条数','required':true,'type':'integer','format':'int32'},{'name':'status','in':'query','required':false,'type':'string','enum':['TODO','DONE','REJECT']}],
        },
        [CommentController.update.method] : {
            summary: '更新',
            method: 'put',
            url: (payload) => `/api/comments`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'意见反馈','$ref':'#/definitions/意见反馈'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
