//This file is automatically generated

// dict-type-controller

import { DictTypeController } from '../controller';
export default {
    actions: {
        [DictTypeController.create.method] : {
            summary: '新增',
            method: 'post',
            url: (payload) => `/api/dict-types`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'DictType','$ref':'#/definitions/DictType'}}],
        },
        [DictTypeController.deleteByIds.method] : {
            summary: '按主键集合(以&#x27;,&#x27;分割)删除',
            method: 'delete',
            url: (payload) => `/api/dict-types/${payload.ids}`,
            parameters: [{'name':'ids','in':'path','description':'ids','required':true,'type':'string'}],
        },
        [DictTypeController.downloadDictTemplate.method] : {
            summary: '下载导入模板',
            method: 'get',
            url: (payload) => `/api/dict-types/download-dict-template`,
            parameters: [],
        },
        [DictTypeController.exportExcelAll.method] : {
            summary: '导出所有数据字典',
            method: 'get',
            url: (payload) => `/api/dict-types/export-all`,
            parameters: [{'name':'locale','in':'query','description':'locale','required':false,'type':'string'}],
        },
        [DictTypeController.exportExcelByCodes.method] : {
            summary: '按给定的 code 批量导出数据字典',
            method: 'get',
            url: (payload) => `/api/dict-types/export-by-codes`,
            parameters: [{'name':'codes','in':'query','description':'codes','required':false,'type':'array','items':{'type':'string'},'collectionFormat':'multi'},{'name':'locale','in':'query','description':'locale','required':false,'type':'string'}],
        },
        [DictTypeController.exportExcelById.method] : {
            summary: '导出父类以及子类的数据字典',
            method: 'get',
            url: (payload) => `/api/dict-types/export-by-id/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'},{'name':'loadChildren','in':'query','description':'loadChildren','required':false,'type':'boolean'},{'name':'locale','in':'query','description':'locale','required':false,'type':'string'}],
        },
        [DictTypeController.exportExcelByIds.method] : {
            summary: '按给定的 id 批量导出数据字典',
            method: 'get',
            url: (payload) => `/api/dict-types/export-by-ids`,
            parameters: [{'name':'ids','in':'query','description':'ids','required':false,'type':'array','items':{'type':'string'},'collectionFormat':'multi'},{'name':'locale','in':'query','description':'locale','required':false,'type':'string'}],
        },
        [DictTypeController.findByCriteria.method] : {
            summary: '分页查询字典类型',
            method: 'get',
            url: (payload) => `/api/dict-types/page-search`,
            parameters: [{'name':'code','in':'query','description':'编码','required':false,'type':'string'},{'name':'id','in':'query','description':'Id','required':false,'type':'string'},{'name':'listRoot','in':'query','description':'是否只查询顶层数据','required':false,'type':'boolean'},{'name':'loadChildren','in':'query','description':'是否加载子节点','required':false,'type':'boolean'},{'name':'loadChildrenLevel','in':'query','description':'从当前层开始，需要加载子节点的层级','required':false,'type':'integer','format':'int32'},{'name':'loadOthers','in':'query','description':'是否加载节点的其它资源','required':false,'type':'boolean'},{'name':'locale','in':'query','required':false,'type':'string'},{'name':'name','in':'query','description':'名称','required':false,'type':'string'},{'name':'pageNum','in':'query','required':false,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','required':false,'type':'integer','format':'int32'},{'name':'parentId','in':'query','description':'父对象的id','required':false,'type':'string'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'}],
        },
        [DictTypeController.findById.method] : {
            summary: '按主键查询',
            method: 'get',
            url: (payload) => `/api/dict-types/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'},{'name':'loadChildren','in':'query','description':'loadChildren','required':false,'type':'boolean'},{'name':'loadLevel','in':'query','description':'loadLevel','required':false,'type':'integer','default':0,'format':'int32'},{'name':'locale','in':'query','description':'locale','required':false,'type':'string'}],
        },
        [DictTypeController.importExcel.method] : {
            summary: '导入字典',
            method: 'post',
            url: (payload) => `/api/dict-types/import`,
            parameters: [{'name':'file','in':'formData','description':'file','required':true,'type':'file'},{'name':'overideExists','in':'query','description':'overideExists','required':false,'type':'boolean'}],
        },
        [DictTypeController.querySubDictEntries.method] : {
            summary: '查询类型下的字典项',
            method: 'get',
            url: (payload) => `/api/dict-types/${payload.id}/dict-entries`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'},{'name':'locale','in':'query','description':'locale','required':false,'type':'string'},{'name':'subDictEntryCode','in':'query','description':'subDictEntryCode','required':false,'type':'string'},{'name':'subDictEntryName','in':'query','description':'subDictEntryName','required':false,'type':'string'}],
        },
        [DictTypeController.update.method] : {
            summary: '更新',
            method: 'put',
            url: (payload) => `/api/dict-types`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'DictType','$ref':'#/definitions/DictType'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
