//This file is automatically generated

// dimension-controller

import { DimensionController } from '../controller';
export default {
    actions: {
        [DimensionController.create.method] : {
            summary: '新增',
            method: 'post',
            url: (payload) => `/api/dimensions`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'维度','$ref':'#/definitions/维度'}}],
        },
        [DimensionController.deleteByIds.method] : {
            summary: '按主键集合删除',
            method: 'put',
            url: (payload) => `/api/dimensions/bulk-delete`,
            parameters: [{'in':'body','name':'ids','description':'ids','required':true,'schema':{'type':'array','items':{'type':'string'}}}],
        },
        [DimensionController.findById.method] : {
            summary: '按主键查询',
            method: 'get',
            url: (payload) => `/api/dimensions/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [DimensionController.queryByCriteria.method] : {
            summary: '按条件查询维度',
            method: 'get',
            url: (payload) => `/api/dimensions/search`,
            parameters: [{'name':'code','in':'query','description':'编码','required':false,'type':'string'},{'name':'id','in':'query','description':'Id','required':false,'type':'string'},{'name':'main','in':'query','required':false,'type':'boolean'},{'name':'name','in':'query','description':'名称','required':false,'type':'string'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'}],
        },
        [DimensionController.update.method] : {
            summary: '更新',
            method: 'put',
            url: (payload) => `/api/dimensions`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'维度','$ref':'#/definitions/维度'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
