//This file is automatically generated

// gateway-route-controller

import { GatewayRouteController } from '../controller';
export default {
    actions: {
        [GatewayRouteController.create.method] : {
            summary: '创建路由',
            method: 'post',
            url: (payload) => `/api/routes`,
            parameters: [{'in':'body','name':'route','description':'route','required':true,'schema':{'originalRef':'Route','$ref':'#/definitions/Route'}}],
        },
        [GatewayRouteController.deleteById.method] : {
            summary: '按主键删除',
            method: 'delete',
            url: (payload) => `/api/routes/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [GatewayRouteController.deleteByIds.method] : {
            summary: '按主键批量删除',
            method: 'put',
            url: (payload) => `/api/routes/bulk-delete`,
            parameters: [{'in':'body','name':'ids','description':'ids','required':true,'schema':{'type':'array','items':{'type':'string'}}}],
        },
        [GatewayRouteController.findByCriteria.method] : {
            summary: '按条件查询',
            method: 'get',
            url: (payload) => `/api/routes/query`,
            parameters: [{'name':'appId','in':'query','required':false,'type':'string'},{'name':'name','in':'query','required':false,'type':'string'},{'name':'usingLikeQuery','in':'query','required':false,'type':'boolean'}],
        },
        [GatewayRouteController.findById.method] : {
            summary: '按主键查询',
            method: 'get',
            url: (payload) => `/api/routes/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [GatewayRouteController.findRouteTemplates.method] : {
            summary: '获取路由模板',
            method: 'get',
            url: (payload) => `/api/routes/templates`,
            parameters: [],
        },
        [GatewayRouteController.pagingByCriteria.method] : {
            summary: '按条件分页查询',
            method: 'get',
            url: (payload) => `/api/routes/page-query`,
            parameters: [{'name':'appId','in':'query','required':false,'type':'string'},{'name':'name','in':'query','required':false,'type':'string'},{'name':'pageNum','in':'query','description':'第几页，从0开始','required':true,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','description':'单页条数','required':true,'type':'integer','format':'int32'},{'name':'usingLikeQuery','in':'query','required':false,'type':'boolean'}],
        },
        [GatewayRouteController.update.method] : {
            summary: '修改路由',
            method: 'put',
            url: (payload) => `/api/routes`,
            parameters: [{'in':'body','name':'route','description':'route','required':true,'schema':{'originalRef':'Route','$ref':'#/definitions/Route'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
