//This file is automatically generated

// gateway-route-valve-rate-controller

import { GatewayRouteValveRateController } from '../controller';
export default {
    actions: {
        [GatewayRouteValveRateController.create.method] : {
            summary: '新增路由限流策略',
            method: 'post',
            url: (payload) => `/api/route-valve-rate`,
            parameters: [{'in':'body','name':'routeValveRate','description':'routeValveRate','required':true,'schema':{'originalRef':'RouteValveRate','$ref':'#/definitions/RouteValveRate'}}],
        },
        [GatewayRouteValveRateController.deleteById.method] : {
            summary: '根据主键删除',
            method: 'delete',
            url: (payload) => `/api/route-valve-rate/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [GatewayRouteValveRateController.findByRouteId.method] : {
            summary: '根据路由id查询',
            method: 'get',
            url: (payload) => `/api/route-valve-rate/routes/${payload.routeId}`,
            parameters: [{'name':'routeId','in':'path','description':'routeId','required':true,'type':'string'}],
        },
        [GatewayRouteValveRateController.update.method] : {
            summary: '修改路由限流策略',
            method: 'put',
            url: (payload) => `/api/route-valve-rate`,
            parameters: [{'in':'body','name':'routeValveRate','description':'routeValveRate','required':true,'schema':{'originalRef':'RouteValveRate','$ref':'#/definitions/RouteValveRate'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
