//This file is automatically generated

// gateway-open-api-controller

import { GatewayOpenApiController } from '../controller';
export default {
    actions: {
        [GatewayOpenApiController.deleteByIds.method] : {
            summary: '批量删除：支持单个和批量',
            method: 'put',
            url: (payload) => `/api/open-apis/bulk-delete`,
            parameters: [{'in':'body','name':'ids','description':'ids','required':true,'schema':{'type':'array','items':{'type':'string'}}}],
        },
        [GatewayOpenApiController.findDetailById.method] : {
            summary: '按主键查询openApi详情',
            method: 'get',
            url: (payload) => `/api/open-apis/${payload.apiId}/detail`,
            parameters: [{'name':'apiId','in':'path','description':'apiId','required':true,'type':'string'}],
        },
        [GatewayOpenApiController.importFromFile.method] : {
            summary: '导入api：从.json文件导入',
            method: 'post',
            url: (payload) => `/api/open-apis/app/${payload.appId}/import-from-file`,
            parameters: [{'name':'appId','in':'path','description':'appId','required':true,'type':'string'},{'name':'file','in':'formData','description':'file','required':true,'type':'file'},{'in':'formData','name':'prefix','description':'prefix','required':true,'schema':{'type':'string'}},{'in':'formData','name':'tags','description':'tags','required':true,'schema':{'type':'string'}}],
        },
        [GatewayOpenApiController.pagingAuthorizationsByCriteria.method] : {
            summary: '按条件分页查询订阅api列表',
            method: 'get',
            url: (payload) => `/api/open-apis/subscribers/${payload.subscriberId}/subscription-open-apis`,
            parameters: [{'name':'alias','in':'query','required':false,'type':'string'},{'name':'apiId','in':'query','required':false,'type':'string'},{'name':'apiName','in':'query','required':false,'type':'string'},{'name':'apiPath','in':'query','required':false,'type':'string'},{'name':'appInstGrpId','in':'query','required':false,'type':'string'},{'name':'authorizedState','in':'query','required':false,'type':'string','enum':['AUTHORIZED','UNAUTHORIZED']},{'name':'authorizedSystemId','in':'query','required':false,'type':'string'},{'name':'gatewayId','in':'query','required':false,'type':'string'},{'name':'pageNum','in':'query','description':'第几页，从0开始','required':true,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','description':'单页条数','required':true,'type':'integer','format':'int32'},{'name':'subscribedState','in':'query','required':false,'type':'string','enum':['AUTHORIZED','UNAUTHORIZED']},{'name':'subscriberId','in':'path','description':'subscriberId','required':true,'type':'string'},{'name':'subscriberId','in':'query','required':false,'type':'string'},{'name':'systemId','in':'query','required':false,'type':'string'},{'name':'tag','in':'query','required':false,'type':'string'},{'name':'usingLikeQuery','in':'query','required':false,'type':'boolean'}],
        },
        [GatewayOpenApiController.pagingByCriteria.method] : {
            summary: '按条件分页查询open-api列表',
            method: 'get',
            url: (payload) => `/api/open-apis/page-query`,
            parameters: [{'name':'alias','in':'query','required':false,'type':'string'},{'name':'appApiIsValid','in':'query','required':false,'type':'boolean'},{'name':'appInstGrpId','in':'query','required':false,'type':'string'},{'name':'gatewayId','in':'query','required':false,'type':'string'},{'name':'name','in':'query','required':false,'type':'string'},{'name':'pageNum','in':'query','description':'第几页，从0开始','required':true,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','description':'单页条数','required':true,'type':'integer','format':'int32'},{'name':'path','in':'query','required':false,'type':'string'},{'name':'state','in':'query','required':false,'type':'string','enum':['PUBLISHED','UNPUBLISHED']},{'name':'tag','in':'query','required':false,'type':'string'},{'name':'usingLikeQuery','in':'query','required':false,'type':'boolean'}],
        },
        [GatewayOpenApiController.publish.method] : {
            summary: 'api发布：单个和批量',
            method: 'put',
            url: (payload) => `/api/open-apis/publish-open-apis`,
            parameters: [{'in':'body','name':'openApiIds','description':'openApiIds','required':true,'schema':{'type':'array','items':{'type':'string'}}}],
        },
        [GatewayOpenApiController.queryTags.method] : {
            summary: '查询标签列表',
            method: 'get',
            url: (payload) => `/api/open-apis/app/${payload.appId}/tags`,
            parameters: [{'name':'appId','in':'path','description':'appId','required':true,'type':'string'}],
        },
        [GatewayOpenApiController.recreateSubscriptionKey.method] : {
            summary: '刷新订阅凭证',
            method: 'put',
            url: (payload) => `/api/open-apis/${payload.appId}/subscription-key`,
            parameters: [{'name':'appId','in':'path','description':'appId','required':true,'type':'string'},{'in':'body','name':'retainOldKey','description':'retainOldKey','required':false,'schema':{'originalRef':'RetainOldKey','$ref':'#/definitions/RetainOldKey'}}],
        },
        [GatewayOpenApiController.subscribe.method] : {
            summary: '订阅api',
            method: 'put',
            url: (payload) => `/api/open-apis/subscribers/${payload.subscriberId}/subscription-open-apis`,
            parameters: [{'in':'body','name':'apiIds','description':'apiIds','required':true,'schema':{'type':'array','items':{'type':'string'}}},{'name':'subscriberId','in':'path','description':'subscriberId','required':true,'type':'string'}],
        },
        [GatewayOpenApiController.unpublish.method] : {
            summary: 'api取消发布：单个和批量',
            method: 'put',
            url: (payload) => `/api/open-apis/unpublish-open-apis`,
            parameters: [{'in':'body','name':'openApiIds','description':'openApiIds','required':true,'schema':{'type':'array','items':{'type':'string'}}}],
        },
        [GatewayOpenApiController.unsubscribe.method] : {
            summary: '取消订阅',
            method: 'put',
            url: (payload) => `/api/open-apis/subscribers/${payload.subscriberId}/unsubscription-open-apis`,
            parameters: [{'in':'body','name':'apiIds','description':'apiIds','required':true,'schema':{'type':'array','items':{'type':'string'}}},{'name':'subscriberId','in':'path','description':'subscriberId','required':true,'type':'string'}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
