//This file is automatically generated

// gateway-configuration-controller

import { GatewayConfigurationController } from '../controller';
export default {
    actions: {
        [GatewayConfigurationController.createApiWhites.method] : {
            summary: '创建api白名单：每次传全量的id',
            method: 'post',
            url: (payload) => `/api/gateway-config/apps/${payload.appId}/api-whitelists`,
            parameters: [{'in':'body','name':'apiIds','description':'apiIds','required':true,'schema':{'type':'array','items':{'type':'string'}}},{'name':'appId','in':'path','description':'appId','required':true,'type':'string'}],
        },
        [GatewayConfigurationController.createDeviceBlacklists.method] : {
            summary: '创建设备号黑名单',
            method: 'post',
            url: (payload) => `/api/gateway-config/apps/${payload.appId}/device-blacklists`,
            parameters: [{'name':'appId','in':'path','description':'appId','required':true,'type':'string'},{'in':'body','name':'devices','description':'devices','required':true,'schema':{'type':'array','items':{'type':'string'}}}],
        },
        [GatewayConfigurationController.createDeviceWhitelists.method] : {
            summary: '创建设备号白名单',
            method: 'post',
            url: (payload) => `/api/gateway-config/apps/${payload.appId}/device-whitelists`,
            parameters: [{'name':'appId','in':'path','description':'appId','required':true,'type':'string'},{'in':'body','name':'devices','description':'devices','required':true,'schema':{'type':'array','items':{'type':'string'}}}],
        },
        [GatewayConfigurationController.queryApiWhitelists.method] : {
            summary: '查询api白名单',
            method: 'get',
            url: (payload) => `/api/gateway-config/apps/${payload.appId}/api-whitelists`,
            parameters: [{'name':'appId','in':'path','description':'appId','required':true,'type':'string'}],
        },
        [GatewayConfigurationController.queryDeviceBlacklists.method] : {
            summary: '查询设备号黑名单列表',
            method: 'get',
            url: (payload) => `/api/gateway-config/apps/${payload.appId}/device-blacklists`,
            parameters: [{'name':'appId','in':'path','description':'appId','required':true,'type':'string'}],
        },
        [GatewayConfigurationController.queryDeviceWhitelists.method] : {
            summary: '查询设备号白名单列表',
            method: 'get',
            url: (payload) => `/api/gateway-config/apps/${payload.appId}/device-whitelists`,
            parameters: [{'name':'appId','in':'path','description':'appId','required':true,'type':'string'}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
