//This file is automatically generated

// gateway-api-access-controller

import { GatewayApiAccessController } from '../controller';
export default {
    actions: {
        [GatewayApiAccessController.findApiPaths.method] : {
            summary: '查询apiPath',
            method: 'get',
            url: (payload) => `/api/api-access-stats/api-paths`,
            parameters: [{'name':'appId','in':'query','required':false,'type':'string'},{'name':'maxSize','in':'query','description':'maxSize','required':false,'type':'integer','default':50,'format':'int32'},{'name':'path','in':'query','required':false,'type':'string'}],
        },
        [GatewayApiAccessController.findTopN.method] : {
            summary: '获取topN',
            method: 'get',
            url: (payload) => `/api/api-access-stats/topn`,
            parameters: [{'name':'appCode','in':'query','required':false,'type':'string'},{'name':'appInstGrpCode','in':'query','required':false,'type':'string'},{'name':'appInstId','in':'query','required':false,'type':'string'},{'name':'dateBegin','in':'query','required':false,'type':'string','format':'date-time'},{'name':'dateEnd','in':'query','required':false,'type':'string','format':'date-time'},{'name':'distinct','in':'query','required':false,'type':'boolean'},{'name':'hashKey','in':'query','required':false,'type':'integer','format':'int32'},{'name':'httpMethod','in':'query','required':false,'type':'string'},{'name':'path','in':'query','required':false,'type':'string'},{'name':'systemCode','in':'query','required':false,'type':'string'},{'name':'timeType','in':'query','required':false,'type':'string','enum':['MINUTE','HOUR','DAY']},{'name':'topN','in':'query','required':false,'type':'integer','format':'int32'},{'name':'topNField','in':'query','required':false,'type':'string'}],
        },
        [GatewayApiAccessController.pagingByCriteria.method] : {
            summary: '分页查询统计信息',
            method: 'get',
            url: (payload) => `/api/api-access-stats/page-query`,
            parameters: [{'name':'appCode','in':'query','required':false,'type':'string'},{'name':'appInstGrpCode','in':'query','required':false,'type':'string'},{'name':'appInstId','in':'query','required':false,'type':'string'},{'name':'dateBegin','in':'query','required':false,'type':'string','format':'date-time'},{'name':'dateEnd','in':'query','required':false,'type':'string','format':'date-time'},{'name':'distinct','in':'query','required':false,'type':'boolean'},{'name':'hashKey','in':'query','required':false,'type':'integer','format':'int32'},{'name':'httpMethod','in':'query','required':false,'type':'string'},{'name':'orderDirection','in':'query','required':false,'type':'string','enum':['ASC','DESC']},{'name':'orderField','in':'query','required':false,'type':'string'},{'name':'pageNum','in':'query','description':'第几页，从0开始','required':true,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','description':'单页条数','required':true,'type':'integer','format':'int32'},{'name':'path','in':'query','required':false,'type':'string'},{'name':'systemCode','in':'query','required':false,'type':'string'},{'name':'timeType','in':'query','required':false,'type':'string','enum':['MINUTE','HOUR','DAY']}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
