//This file is automatically generated

// iam-device-controller

import { IamDeviceController } from '../controller';
export default {
    actions: {
        [IamDeviceController.create.method] : {
            summary: '新增',
            method: 'post',
            url: (payload) => `/api/iam-devices`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'Device','$ref':'#/definitions/Device'}}],
        },
        [IamDeviceController.deleteById.method] : {
            summary: '按主键删除',
            method: 'delete',
            url: (payload) => `/api/iam-devices/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [IamDeviceController.deleteByIds.method] : {
            summary: '按主键集合删除',
            method: 'put',
            url: (payload) => `/api/iam-devices/bulk-delete`,
            parameters: [{'in':'body','name':'ids','description':'ids','required':true,'schema':{'type':'array','items':{'type':'string'}}}],
        },
        [IamDeviceController.findByCriteria.method] : {
            summary: '按条件查询',
            method: 'get',
            url: (payload) => `/api/iam-devices/query`,
            parameters: [{'name':'deviceId','in':'query','description':'设备Id','required':false,'type':'string'},{'name':'deviceName','in':'query','description':'设备名称','required':false,'type':'string'},{'name':'deviceType','in':'query','description':'设备类型','required':false,'type':'string','enum':['ANDROID','IOS']},{'name':'status','in':'query','description':'设备状态','required':false,'type':'string','enum':['ENABLED','DISABLED']},{'name':'userId','in':'query','description':'用户Id','required':false,'type':'string'}],
        },
        [IamDeviceController.findByDeviceIds.method] : {
            summary: '按deviceId集合查询设备信息',
            method: 'post',
            url: (payload) => `/api/iam-devices/bulk-query`,
            parameters: [{'in':'body','name':'ids','description':'ids','required':true,'schema':{'type':'array','items':{'type':'string'}}}],
        },
        [IamDeviceController.findById.method] : {
            summary: '按主键查询',
            method: 'get',
            url: (payload) => `/api/iam-devices/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [IamDeviceController.pageByCriteria.method] : {
            summary: '按条件分页查询',
            method: 'get',
            url: (payload) => `/api/iam-devices/page-query`,
            parameters: [{'name':'deviceId','in':'query','description':'设备Id','required':false,'type':'string'},{'name':'deviceName','in':'query','description':'设备名称','required':false,'type':'string'},{'name':'deviceType','in':'query','description':'设备类型','required':false,'type':'string','enum':['ANDROID','IOS']},{'name':'pageNum','in':'query','description':'第几页，从0开始','required':true,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','description':'单页条数','required':true,'type':'integer','format':'int32'},{'name':'status','in':'query','description':'设备状态','required':false,'type':'string','enum':['ENABLED','DISABLED']},{'name':'userId','in':'query','description':'用户Id','required':false,'type':'string'}],
        },
        [IamDeviceController.update.method] : {
            summary: '更新',
            method: 'put',
            url: (payload) => `/api/iam-devices`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'Device','$ref':'#/definitions/Device'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
