//This file is automatically generated

// iam-login-config-controller

import { IamLoginConfigController } from '../controller';
export default {
    actions: {
        [IamLoginConfigController.create.method] : {
            summary: '新增',
            method: 'post',
            url: (payload) => `/api/iam-login-configs`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'登录配置','$ref':'#/definitions/登录配置'}}],
        },
        [IamLoginConfigController.deleteById.method] : {
            summary: '按主键删除',
            method: 'delete',
            url: (payload) => `/api/iam-login-configs/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [IamLoginConfigController.deleteByIds.method] : {
            summary: '按主键集合删除',
            method: 'put',
            url: (payload) => `/api/iam-login-configs/bulk-delete`,
            parameters: [{'in':'body','name':'ids','description':'ids','required':true,'schema':{'type':'array','items':{'type':'string'}}}],
        },
        [IamLoginConfigController.findByCriteria.method] : {
            summary: '按条件查询',
            method: 'get',
            url: (payload) => `/api/iam-login-configs/query`,
            parameters: [{'name':'code','in':'query','description':'编码','required':false,'type':'string'},{'name':'id','in':'query','description':'Id','required':false,'type':'string'},{'name':'name','in':'query','description':'名称','required':false,'type':'string'},{'name':'tenantId','in':'query','description':'tenantId','required':false,'type':'string'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'}],
        },
        [IamLoginConfigController.findById.method] : {
            summary: '按主键查询',
            method: 'get',
            url: (payload) => `/api/iam-login-configs/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [IamLoginConfigController.findLoginConfigByAppId.method] : {
            summary: '根据appId查找登录配置',
            method: 'get',
            url: (payload) => `/api/iam-login-configs/${payload.appId}/login-config`,
            parameters: [{'name':'appId','in':'path','description':'appId','required':true,'type':'string'}],
        },
        [IamLoginConfigController.pageByCriteria.method] : {
            summary: '按条件分页查询',
            method: 'get',
            url: (payload) => `/api/iam-login-configs/page-query`,
            parameters: [{'name':'code','in':'query','description':'编码','required':false,'type':'string'},{'name':'id','in':'query','description':'Id','required':false,'type':'string'},{'name':'name','in':'query','description':'名称','required':false,'type':'string'},{'name':'pageNum','in':'query','description':'第几页，从0开始','required':true,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','description':'单页条数','required':true,'type':'integer','format':'int32'},{'name':'tenantId','in':'query','description':'tenantId','required':false,'type':'string'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'}],
        },
        [IamLoginConfigController.update.method] : {
            summary: '更新',
            method: 'put',
            url: (payload) => `/api/iam-login-configs`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'登录配置','$ref':'#/definitions/登录配置'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
