//This file is automatically generated

// iam-org-controller

import { IamOrgController } from '../controller';
export default {
    actions: {
        [IamOrgController.addOrgEmployees.method] : {
            summary: '往机构下批量添加员工',
            method: 'put',
            url: (payload) => `/api/iam-orgs/${payload.id}/employees/add`,
            parameters: [{'in':'body','name':'employeeIds','description':'employeeIds','required':true,'schema':{'type':'array','items':{'type':'string'}}},{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [IamOrgController.create.method] : {
            summary: '新增',
            method: 'post',
            url: (payload) => `/api/iam-orgs`,
            parameters: [{'in':'body','name':'organization','description':'organization','required':true,'schema':{'originalRef':'机构','$ref':'#/definitions/机构'}}],
        },
        [IamOrgController.deleteByIds.method] : {
            summary: '按主键集合删除',
            method: 'put',
            url: (payload) => `/api/iam-orgs/bulk-delete`,
            parameters: [{'in':'body','name':'ids','description':'ids','required':true,'schema':{'type':'array','items':{'type':'string'}}}],
        },
        [IamOrgController.findById.method] : {
            summary: '按主键查询',
            method: 'get',
            url: (payload) => `/api/iam-orgs/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'},{'name':'loadChildren','in':'query','description':'loadChildren','required':false,'type':'boolean'},{'name':'loadLevel','in':'query','description':'loadLevel','required':false,'type':'integer','default':1,'format':'int32'},{'name':'loadOthers','in':'query','description':'loadOthers','required':false,'type':'boolean'}],
        },
        [IamOrgController.findByIds.method] : {
            summary: '根据Id批量查询机构',
            method: 'post',
            url: (payload) => `/api/iam-orgs/query/by-ids`,
            parameters: [{'in':'body','name':'ids','description':'ids','required':true,'schema':{'type':'array','items':{'type':'string'}}}],
        },
        [IamOrgController.pagingByCriteria.method] : {
            summary: '按条件分页查询',
            method: 'get',
            url: (payload) => `/api/iam-orgs/page-query`,
            parameters: [{'name':'area','in':'query','required':false,'type':'string'},{'name':'code','in':'query','description':'编码','required':false,'type':'string'},{'name':'dimensionCode','in':'query','required':false,'type':'string'},{'name':'dimensionId','in':'query','required':false,'type':'string'},{'name':'id','in':'query','description':'Id','required':false,'type':'string'},{'name':'listRoot','in':'query','description':'是否只查询顶层数据','required':false,'type':'boolean'},{'name':'loadChildren','in':'query','description':'是否加载子节点','required':false,'type':'boolean'},{'name':'loadChildrenLevel','in':'query','description':'从当前层开始，需要加载子节点的层级','required':false,'type':'integer','format':'int32'},{'name':'loadOthers','in':'query','description':'是否加载节点的其它资源','required':false,'type':'boolean'},{'name':'name','in':'query','description':'名称','required':false,'type':'string'},{'name':'pageNum','in':'query','description':'第几页，从0开始','required':true,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','description':'单页条数','required':true,'type':'integer','format':'int32'},{'name':'parentId','in':'query','description':'父对象的id','required':false,'type':'string'},{'name':'status','in':'query','required':false,'type':'string'},{'name':'strategy','in':'query','required':false,'type':'string','enum':['NONE','CURRENT','ALL']},{'name':'tenantId','in':'query','description':'tenantId','required':false,'type':'string'},{'name':'type','in':'query','required':false,'type':'string'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'}],
        },
        [IamOrgController.queryEmpOrg.method] : {
            summary: '查询员工���在当前机构',
            method: 'get',
            url: (payload) => `/api/iam-orgs/${payload.id}/orgs`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [IamOrgController.queryOrgTree.method] : {
            summary: '查询当前机构的所有父机构',
            method: 'get',
            url: (payload) => `/api/iam-orgs/orgTree`,
            parameters: [{'name':'orgIds','in':'query','description':'orgIds','required':true,'type':'array','items':{'type':'string'},'collectionFormat':'multi'}],
        },
        [IamOrgController.querySubEmployees.method] : {
            summary: '查询机构下的员工',
            method: 'get',
            url: (payload) => `/api/iam-orgs/${payload.id}/employees`,
            parameters: [{'name':'employeeName','in':'query','description':'employeeName','required':false,'type':'string'},{'name':'id','in':'path','description':'id','required':true,'type':'string'},{'name':'pageNum','in':'query','description':'第几页，从0开始','required':true,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','description':'单页条数','required':true,'type':'integer','format':'int32'}],
        },
        [IamOrgController.querySubOrganizations.method] : {
            summary: '查询当前机构的所有子机构',
            method: 'get',
            url: (payload) => `/api/iam-orgs/${payload.orgId}/subOrganizations`,
            parameters: [{'name':'orgId','in':'path','description':'orgId','required':true,'type':'string'}],
        },
        [IamOrgController.querySubPositions.method] : {
            summary: '查询机构下的岗位',
            method: 'get',
            url: (payload) => `/api/iam-orgs/${payload.id}/positions`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'},{'name':'pageNum','in':'query','description':'第几页，从0开始','required':true,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','description':'单页条数','required':true,'type':'integer','format':'int32'},{'name':'positionCode','in':'query','description':'positionCode','required':false,'type':'string'},{'name':'positionName','in':'query','description':'positionName','required':false,'type':'string'}],
        },
        [IamOrgController.removeOrgEmployees.method] : {
            summary: '从机构下批量移除员工',
            method: 'put',
            url: (payload) => `/api/iam-orgs/${payload.id}/employees/remove`,
            parameters: [{'in':'body','name':'employeeIds','description':'employeeIds','required':true,'schema':{'type':'array','items':{'type':'string'}}},{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [IamOrgController.update.method] : {
            summary: '更新',
            method: 'put',
            url: (payload) => `/api/iam-orgs`,
            parameters: [{'in':'body','name':'organization','description':'organization','required':true,'schema':{'originalRef':'机构','$ref':'#/definitions/机构'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
