//This file is automatically generated

// license-controller

import { LicenseController } from '../controller';
export default {
    actions: {
        [LicenseController.getLicense.method] : {
            summary: '移动License-获取License信息',
            method: 'get',
            url: (payload) => `/api/license`,
            parameters: [],
        },
        [LicenseController.uploadLicense.method] : {
            summary: '移动License-上传License文件',
            method: 'post',
            url: (payload) => `/api/license/upload`,
            parameters: [{'name':'file','in':'formData','description':'file','required':true,'type':'file'}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
