//This file is automatically generated

// microapp-archive-controller

import { MicroappArchiveController } from '../controller';
export default {
    actions: {
        [MicroappArchiveController.create.method] : {
            summary: '新增',
            method: 'post',
            url: (payload) => `/api/microapp-archives`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'微应用介质','$ref':'#/definitions/微应用介质'}}],
        },
        [MicroappArchiveController.deleteById.method] : {
            summary: '按主键删除',
            method: 'delete',
            url: (payload) => `/api/microapp-archives/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [MicroappArchiveController.deleteByIds.method] : {
            summary: '按主键集合删除',
            method: 'put',
            url: (payload) => `/api/microapp-archives/bulk-delete`,
            parameters: [{'in':'body','name':'ids','description':'ids','required':true,'schema':{'type':'array','items':{'type':'string'}}}],
        },
        [MicroappArchiveController.findByCriteria.method] : {
            summary: '按条件查询',
            method: 'get',
            url: (payload) => `/api/microapp-archives/query`,
            parameters: [{'name':'build','in':'query','required':false,'type':'string'},{'name':'id','in':'query','description':'id','required':false,'type':'string'},{'name':'loadDownloadCount','in':'query','required':false,'type':'boolean'},{'name':'microappId','in':'query','required':false,'type':'string'},{'name':'status','in':'query','required':false,'type':'string','enum':['CREATED','GRAYSCALE','ONLINE','OFFLINE']},{'name':'tenantId','in':'query','description':'租户id','required':false,'type':'string'},{'name':'updateMode','in':'query','required':false,'type':'string','enum':['FORCE','OPTIONAL','SILENCE']},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'},{'name':'version','in':'query','required':false,'type':'string'}],
        },
        [MicroappArchiveController.findById.method] : {
            summary: '按主键查询',
            method: 'get',
            url: (payload) => `/api/microapp-archives/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [MicroappArchiveController.handleWhitelist.method] : {
            summary: '授权',
            method: 'put',
            url: (payload) => `/api/microapp-archives/${payload.id}/whitelist`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'},{'in':'body','name':'operatableAuths','description':'operatableAuths','required':true,'schema':{'type':'array','items':{'originalRef':'操作授权','$ref':'#/definitions/操作授权'}}}],
        },
        [MicroappArchiveController.loadWhitelist.method] : {
            summary: '获取授权',
            method: 'get',
            url: (payload) => `/api/microapp-archives/${payload.id}/whitelist`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [MicroappArchiveController.pageByCriteria.method] : {
            summary: '按条件分页查询',
            method: 'get',
            url: (payload) => `/api/microapp-archives/page-query`,
            parameters: [{'name':'build','in':'query','required':false,'type':'string'},{'name':'id','in':'query','description':'id','required':false,'type':'string'},{'name':'loadDownloadCount','in':'query','required':false,'type':'boolean'},{'name':'microappId','in':'query','required':false,'type':'string'},{'name':'pageNum','in':'query','description':'第几页，从0开始','required':true,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','description':'单页条数','required':true,'type':'integer','format':'int32'},{'name':'status','in':'query','required':false,'type':'string','enum':['CREATED','GRAYSCALE','ONLINE','OFFLINE']},{'name':'tenantId','in':'query','description':'租户id','required':false,'type':'string'},{'name':'updateMode','in':'query','required':false,'type':'string','enum':['FORCE','OPTIONAL','SILENCE']},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'},{'name':'version','in':'query','required':false,'type':'string'}],
        },
        [MicroappArchiveController.update.method] : {
            summary: '更新',
            method: 'put',
            url: (payload) => `/api/microapp-archives`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'微应用介质','$ref':'#/definitions/微应用介质'}}],
        },
        [MicroappArchiveController.uploadMicroappArchive.method] : {
            summary: '微应用介质上传',
            method: 'post',
            url: (payload) => `/api/microapp-archives/upload/archive`,
            parameters: [{'name':'archive','in':'formData','description':'archive','required':true,'type':'file'},{'in':'formData','name':'microappType','description':'microappType','required':true,'schema':{'type':'string','enum':['NATIVE','HTML5','REACT_NATIVE','PRIMETON_MOBILE']}}],
        },
        [MicroappArchiveController.uploadPreviews.method] : {
            summary: '上传预览图',
            method: 'post',
            url: (payload) => `/api/microapp-archives/upload/previews`,
            parameters: [{'name':'previews','in':'formData','description':'previews','required':true,'type':'array','items':{'type':'file'},'collectionFormat':'multi'}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
