//This file is automatically generated

// microapp-controller

import { MicroappController } from '../controller';
export default {
    actions: {
        [MicroappController.create.method] : {
            summary: '新增',
            method: 'post',
            url: (payload) => `/api/microapps`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'微应用信息','$ref':'#/definitions/微应用信息'}}],
        },
        [MicroappController.deleteById.method] : {
            summary: '按主键删除',
            method: 'delete',
            url: (payload) => `/api/microapps/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [MicroappController.deleteByIds.method] : {
            summary: '按主键集合删除',
            method: 'put',
            url: (payload) => `/api/microapps/bulk-delete`,
            parameters: [{'in':'body','name':'ids','description':'ids','required':true,'schema':{'type':'array','items':{'type':'string'}}}],
        },
        [MicroappController.findByCriteria.method] : {
            summary: '按条件查询',
            method: 'get',
            url: (payload) => `/api/microapps/query`,
            parameters: [{'name':'appId','in':'query','required':false,'type':'string'},{'name':'id','in':'query','description':'id','required':false,'type':'string'},{'name':'mainMicroapp','in':'query','required':false,'type':'boolean'},{'name':'microappGroupId','in':'query','required':false,'type':'string'},{'name':'microappId','in':'query','required':false,'type':'string'},{'name':'microappName','in':'query','required':false,'type':'string'},{'name':'microappType','in':'query','required':false,'type':'string','enum':['NATIVE','HTML5','REACT_NATIVE','PRIMETON_MOBILE']},{'name':'subscriptionKey','in':'query','required':false,'type':'string'},{'name':'tenantId','in':'query','description':'租户id','required':false,'type':'string'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'},{'name':'usingMainMicroapp','in':'query','required':false,'type':'boolean'}],
        },
        [MicroappController.findById.method] : {
            summary: '按主键查询',
            method: 'get',
            url: (payload) => `/api/microapps/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [MicroappController.pageByCriteria.method] : {
            summary: '按条件分页查询',
            method: 'get',
            url: (payload) => `/api/microapps/page-query`,
            parameters: [{'name':'appId','in':'query','required':false,'type':'string'},{'name':'id','in':'query','description':'id','required':false,'type':'string'},{'name':'mainMicroapp','in':'query','required':false,'type':'boolean'},{'name':'microappGroupId','in':'query','required':false,'type':'string'},{'name':'microappId','in':'query','required':false,'type':'string'},{'name':'microappName','in':'query','required':false,'type':'string'},{'name':'microappType','in':'query','required':false,'type':'string','enum':['NATIVE','HTML5','REACT_NATIVE','PRIMETON_MOBILE']},{'name':'pageNum','in':'query','description':'第几页，从0开始','required':true,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','description':'单页条数','required':true,'type':'integer','format':'int32'},{'name':'subscriptionKey','in':'query','required':false,'type':'string'},{'name':'tenantId','in':'query','description':'租户id','required':false,'type':'string'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'},{'name':'usingMainMicroapp','in':'query','required':false,'type':'boolean'}],
        },
        [MicroappController.update.method] : {
            summary: '更新',
            method: 'put',
            url: (payload) => `/api/microapps`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'微应用信息','$ref':'#/definitions/微应用信息'}}],
        },
        [MicroappController.uploadIcon.method] : {
            summary: '上传图标',
            method: 'post',
            url: (payload) => `/api/microapps/upload/icon`,
            parameters: [{'name':'icon','in':'formData','description':'icon','required':true,'type':'file'}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
