//This file is automatically generated

// microapp-group-controller

import { MicroappGroupController } from '../controller';
export default {
    actions: {
        [MicroappGroupController.addMicroappGroupMicroapps.method] : {
            summary: '添加微应用到分组',
            method: 'put',
            url: (payload) => `/api/microapp-groups/${payload.id}/microapps/${payload.microappIds}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'},{'name':'microappIds','in':'path','description':'microappIds','required':true,'type':'string'}],
        },
        [MicroappGroupController.create.method] : {
            summary: '新增',
            method: 'post',
            url: (payload) => `/api/microapp-groups`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'MicroappGroup','$ref':'#/definitions/MicroappGroup'}}],
        },
        [MicroappGroupController.deleteById.method] : {
            summary: '按主键删除',
            method: 'delete',
            url: (payload) => `/api/microapp-groups/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [MicroappGroupController.deleteByIds.method] : {
            summary: '按主键集合删除',
            method: 'put',
            url: (payload) => `/api/microapp-groups/bulk-delete`,
            parameters: [{'in':'body','name':'ids','description':'ids','required':true,'schema':{'type':'array','items':{'type':'string'}}}],
        },
        [MicroappGroupController.findByCriteria.method] : {
            summary: '按条件查询',
            method: 'get',
            url: (payload) => `/api/microapp-groups/query`,
            parameters: [{'name':'appId','in':'query','required':false,'type':'string'},{'name':'id','in':'query','description':'id','required':false,'type':'string'},{'name':'loadMicroapps','in':'query','required':false,'type':'boolean'},{'name':'loadMicroappsSize','in':'query','required':false,'type':'boolean'},{'name':'microappGroupName','in':'query','required':false,'type':'string'},{'name':'tenantId','in':'query','description':'租户id','required':false,'type':'string'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'}],
        },
        [MicroappGroupController.findById.method] : {
            summary: '按主键查询',
            method: 'get',
            url: (payload) => `/api/microapp-groups/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [MicroappGroupController.pageByCriteria.method] : {
            summary: '按条件分页查询',
            method: 'get',
            url: (payload) => `/api/microapp-groups/page-query`,
            parameters: [{'name':'appId','in':'query','required':false,'type':'string'},{'name':'id','in':'query','description':'id','required':false,'type':'string'},{'name':'loadMicroapps','in':'query','required':false,'type':'boolean'},{'name':'loadMicroappsSize','in':'query','required':false,'type':'boolean'},{'name':'microappGroupName','in':'query','required':false,'type':'string'},{'name':'pageNum','in':'query','description':'第几页，从0开始','required':true,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','description':'单页条数','required':true,'type':'integer','format':'int32'},{'name':'tenantId','in':'query','description':'租户id','required':false,'type':'string'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'}],
        },
        [MicroappGroupController.removeMicroappGroupMicroapps.method] : {
            summary: '移除分组中的微应用',
            method: 'delete',
            url: (payload) => `/api/microapp-groups/${payload.id}/microapps/${payload.microappIds}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'},{'name':'microappIds','in':'path','description':'microappIds','required':true,'type':'string'}],
        },
        [MicroappGroupController.update.method] : {
            summary: '更新',
            method: 'put',
            url: (payload) => `/api/microapp-groups`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'MicroappGroup','$ref':'#/definitions/MicroappGroup'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
