//This file is automatically generated

// operation-log-controller

import { OperationLogController } from '../controller';
export default {
    actions: {
        [OperationLogController.getOperationLogDetail.method] : {
            summary: '获取操作日志详细',
            method: 'get',
            url: (payload) => `/api/operation-logs/logs/${payload.logId}`,
            parameters: [{'name':'logId','in':'path','description':'logId','required':true,'type':'string'}],
        },
        [OperationLogController.pagingOperationLogs.method] : {
            summary: '分页查询操作日志',
            method: 'get',
            url: (payload) => `/api/operation-logs/logs`,
            parameters: [{'name':'dateBegin','in':'query','required':false,'type':'string','format':'date-time'},{'name':'dateEnd','in':'query','required':false,'type':'string','format':'date-time'},{'name':'operateType','in':'query','required':false,'type':'string','enum':['CREATE','UPDATE','DELETE','OTHER']},{'name':'operatorId','in':'query','required':false,'type':'string'},{'name':'pageNum','in':'query','required':false,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','required':false,'type':'integer','format':'int32'}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
