//This file is automatically generated

// organization-controller

import { OrganizationController } from '../controller';
export default {
    actions: {
        [OrganizationController.addOrgEmployees.method] : {
            summary: '往机构下批量添加员工',
            method: 'put',
            url: (payload) => `/api/organizations/${payload.id}/employees/${payload.employeeIds}`,
            parameters: [{'name':'employeeIds','in':'path','description':'employeeIds','required':true,'type':'string'},{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [OrganizationController.create.method] : {
            summary: '新增',
            method: 'post',
            url: (payload) => `/api/organizations`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'机构','$ref':'#/definitions/机构'}}],
        },
        [OrganizationController.deleteByIds.method] : {
            summary: '按主键集合(以&#x27;,&#x27;分割)删除',
            method: 'delete',
            url: (payload) => `/api/organizations/${payload.ids}`,
            parameters: [{'name':'ids','in':'path','description':'ids','required':true,'type':'string'}],
        },
        [OrganizationController.findById.method] : {
            summary: '按主键查询',
            method: 'get',
            url: (payload) => `/api/organizations/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'},{'name':'loadChildren','in':'query','description':'loadChildren','required':false,'type':'boolean'},{'name':'loadLevel','in':'query','description':'loadLevel','required':false,'type':'integer','default':1,'format':'int32'},{'name':'loadOthers','in':'query','description':'loadOthers','required':false,'type':'boolean'}],
        },
        [OrganizationController.pagingByCriteria.method] : {
            summary: '分页查询',
            method: 'get',
            url: (payload) => `/api/organizations/page-search`,
            parameters: [{'name':'area','in':'query','required':false,'type':'string'},{'name':'code','in':'query','description':'编码','required':false,'type':'string'},{'name':'dimension','in':'query','required':false,'type':'string'},{'name':'dimensionCode','in':'query','required':false,'type':'string'},{'name':'dimensionId','in':'query','required':false,'type':'string'},{'name':'id','in':'query','description':'Id','required':false,'type':'string'},{'name':'listRoot','in':'query','description':'是否只查询顶层数据','required':false,'type':'boolean'},{'name':'loadChildren','in':'query','description':'是否加载子节点','required':false,'type':'boolean'},{'name':'loadChildrenLevel','in':'query','description':'从当前层开始，需要加载子节点的层级','required':false,'type':'integer','format':'int32'},{'name':'loadOthers','in':'query','description':'是否加载节点的其它资源','required':false,'type':'boolean'},{'name':'name','in':'query','description':'名称','required':false,'type':'string'},{'name':'pageNum','in':'query','required':false,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','required':false,'type':'integer','format':'int32'},{'name':'parentId','in':'query','description':'父对象的id','required':false,'type':'string'},{'name':'status','in':'query','required':false,'type':'string'},{'name':'strategy','in':'query','required':false,'type':'string','enum':['NONE','CURRENT','ALL']},{'name':'type','in':'query','required':false,'type':'string'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'}],
        },
        [OrganizationController.querySubEmployees.method] : {
            summary: '查询机构下的员工',
            method: 'get',
            url: (payload) => `/api/organizations/${payload.id}/employees`,
            parameters: [{'name':'employeeName','in':'query','description':'employeeName','required':false,'type':'string'},{'name':'id','in':'path','description':'id','required':true,'type':'string'},{'name':'pageNum','in':'query','required':false,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','required':false,'type':'integer','format':'int32'}],
        },
        [OrganizationController.querySubPositions.method] : {
            summary: '查询机构下的岗位',
            method: 'get',
            url: (payload) => `/api/organizations/${payload.id}/positions`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'},{'name':'pageNum','in':'query','required':false,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','required':false,'type':'integer','format':'int32'},{'name':'positionCode','in':'query','description':'positionCode','required':false,'type':'string'},{'name':'positionName','in':'query','description':'positionName','required':false,'type':'string'}],
        },
        [OrganizationController.querySubWorkgroups.method] : {
            summary: '查询机构下的工作组',
            method: 'get',
            url: (payload) => `/api/organizations/${payload.id}/workgroups`,
            parameters: [{'name':'groupName','in':'query','description':'groupName','required':false,'type':'string'},{'name':'id','in':'path','description':'id','required':true,'type':'string'},{'name':'pageNum','in':'query','required':false,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','required':false,'type':'integer','format':'int32'}],
        },
        [OrganizationController.removeOrgEmployees.method] : {
            summary: '从机构下批量移除员工',
            method: 'delete',
            url: (payload) => `/api/organizations/${payload.id}/employees/${payload.employeeIds}`,
            parameters: [{'name':'employeeIds','in':'path','description':'employeeIds','required':true,'type':'string'},{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [OrganizationController.update.method] : {
            summary: '更新',
            method: 'put',
            url: (payload) => `/api/organizations`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'机构','$ref':'#/definitions/机构'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
