//This file is automatically generated

// original-message-controller

import { OriginalMessageController } from '../controller';
export default {
    actions: {
        [OriginalMessageController.create.method] : {
            summary: '新增',
            method: 'post',
            url: (payload) => `/api/original-messages`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'原始推送数据','$ref':'#/definitions/原始推送数据'}}],
        },
        [OriginalMessageController.deleteById.method] : {
            summary: '按主键删除',
            method: 'delete',
            url: (payload) => `/api/original-messages/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [OriginalMessageController.deleteByIds.method] : {
            summary: '按主键集合删除',
            method: 'put',
            url: (payload) => `/api/original-messages/bulk-delete`,
            parameters: [{'in':'body','name':'ids','description':'ids','required':true,'schema':{'type':'array','items':{'type':'string'}}}],
        },
        [OriginalMessageController.findByCriteria.method] : {
            summary: '按条件查询',
            method: 'get',
            url: (payload) => `/api/original-messages/query`,
            parameters: [{'name':'appId','in':'query','required':false,'type':'string'},{'name':'clientCode','in':'query','required':false,'type':'string'},{'name':'messageType','in':'query','required':false,'type':'string','enum':['NOTIFICATION','PASSTHROUGH','EMAIL','WEIXIN_TEMPLATE']},{'name':'priority','in':'query','required':false,'type':'string','enum':['NORMAL','HIGH']},{'name':'pushEnv','in':'query','required':false,'type':'string','enum':['DEV','PRO']},{'name':'pushType','in':'query','required':false,'type':'string','enum':['SIMPLE','TEMPLATE']},{'name':'status','in':'query','required':false,'type':'string','enum':['CREATED','FAILURE','EXPIRED','ASSEMBLED']},{'name':'targetType','in':'query','required':false,'type':'string','enum':['EMP','USER','DEVICE','EMAIL','BROADCAST']},{'name':'taskName','in':'query','required':false,'type':'string'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'}],
        },
        [OriginalMessageController.findById.method] : {
            summary: '按主键查询',
            method: 'get',
            url: (payload) => `/api/original-messages/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [OriginalMessageController.pageByCriteria.method] : {
            summary: '按条件分页查询',
            method: 'get',
            url: (payload) => `/api/original-messages/page-query`,
            parameters: [{'name':'appId','in':'query','required':false,'type':'string'},{'name':'clientCode','in':'query','required':false,'type':'string'},{'name':'messageType','in':'query','required':false,'type':'string','enum':['NOTIFICATION','PASSTHROUGH','EMAIL','WEIXIN_TEMPLATE']},{'name':'pageNum','in':'query','description':'第几页，从0开始','required':true,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','description':'单页条数','required':true,'type':'integer','format':'int32'},{'name':'priority','in':'query','required':false,'type':'string','enum':['NORMAL','HIGH']},{'name':'pushEnv','in':'query','required':false,'type':'string','enum':['DEV','PRO']},{'name':'pushType','in':'query','required':false,'type':'string','enum':['SIMPLE','TEMPLATE']},{'name':'status','in':'query','required':false,'type':'string','enum':['CREATED','FAILURE','EXPIRED','ASSEMBLED']},{'name':'targetType','in':'query','required':false,'type':'string','enum':['EMP','USER','DEVICE','EMAIL','BROADCAST']},{'name':'taskName','in':'query','required':false,'type':'string'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'}],
        },
        [OriginalMessageController.update.method] : {
            summary: '更新',
            method: 'put',
            url: (payload) => `/api/original-messages`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'原始推送数据','$ref':'#/definitions/原始推送数据'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
