//This file is automatically generated

// overview-controller

import { OverviewController } from '../controller';
export default {
    actions: {
        [OverviewController.getOverview.method] : {
            summary: '获取平台概要',
            method: 'get',
            url: (payload) => `/api/overview`,
            parameters: [],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
