//This file is automatically generated

// portal-user-controller

import { PortalUserController } from '../controller';
export default {
    actions: {
        [PortalUserController.pagingByCriteria.method] : {
            summary: '分页查询所有用户',
            method: 'get',
            url: (payload) => `/api/portal-users/page-query`,
            parameters: [{'name':'bindState','in':'query','description':'绑定状态过滤，binded 或者 unBinded，或者不给为空不过滤','required':false,'type':'string'},{'name':'employeeId','in':'query','required':false,'type':'string'},{'name':'filterSys','in':'query','required':false,'type':'boolean'},{'name':'id','in':'query','description':'Id','required':false,'type':'string'},{'name':'memberState','in':'query','description':'成员相关，成员状态，取值为 isMember 或 notMember。此值需 ownerType 与 ownerId 也同时赋值才意义。isMember 查询为此领域成员的用户，notMember 则查询不为此领域成员的用户，用于往某领域内添加成员时的用户过滤','required':false,'type':'string'},{'name':'name','in':'query','description':'名称','required':false,'type':'string'},{'name':'ownerId','in':'query','description':'成员相关，成员所属的领域Id','required':false,'type':'string'},{'name':'ownerType','in':'query','description':'成员相关，成员所属的领域类型','required':false,'type':'string'},{'name':'pageNum','in':'query','description':'第几页，从0开始','required':true,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','description':'单页条数','required':true,'type':'integer','format':'int32'},{'name':'status','in':'query','required':false,'type':'string'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
