//This file is automatically generated

// portal-role-controller

import { PortalRoleController } from '../controller';
export default {
    actions: {
        [PortalRoleController.pagingByCriteria.method] : {
            summary: '分页查询所有角色',
            method: 'get',
            url: (payload) => `/api/portal-roles/page-query`,
            parameters: [{'name':'code','in':'query','description':'编码','required':false,'type':'string'},{'name':'id','in':'query','description':'Id','required':false,'type':'string'},{'name':'listPlatformRoles','in':'query','required':false,'type':'boolean'},{'name':'name','in':'query','description':'名称','required':false,'type':'string'},{'name':'ownerId','in':'query','required':false,'type':'string'},{'name':'ownerType','in':'query','required':false,'type':'string'},{'name':'pageNum','in':'query','description':'第几页，从0开始','required':true,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','description':'单页条数','required':true,'type':'integer','format':'int32'},{'name':'roleTplId','in':'query','required':false,'type':'string'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
