//This file is automatically generated

// portal-member-controller

import { PortalMemberController } from '../controller';
export default {
    actions: {
        [PortalMemberController.pagingMembers.method] : {
            summary: '分页查询所有成员',
            method: 'get',
            url: (payload) => `/api/portal-members/page-query`,
            parameters: [{'name':'filterSys','in':'query','description':'filterSys','required':true,'type':'boolean'},{'name':'ownerId','in':'query','description':'ownerId','required':true,'type':'string'},{'name':'ownerType','in':'query','description':'ownerType','required':true,'type':'string'},{'name':'pageNum','in':'query','description':'第几页，从0开始','required':true,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','description':'单页条数','required':true,'type':'integer','format':'int32'},{'name':'userName','in':'query','description':'userName','required':false,'type':'string'}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
