//This file is automatically generated

// push-collect-stat-controller

import { PushCollectStatController } from '../controller';
export default {
    actions: {
        [PushCollectStatController.findByCriteria.method] : {
            summary: '按条件查询, 用于折线图,柱状图',
            method: 'get',
            url: (payload) => `/api/collect-stats/query`,
            parameters: [{'name':'appId','in':'query','required':false,'type':'string'},{'name':'clientCode','in':'query','required':false,'type':'string'},{'name':'dateBegin','in':'query','required':false,'type':'string','format':'date-time'},{'name':'dateEnd','in':'query','required':false,'type':'string','format':'date-time'},{'name':'extFlag','in':'query','required':false,'type':'integer','format':'int32'},{'name':'pushType','in':'query','required':false,'type':'string','enum':['SIMPLE','TEMPLATE']},{'name':'timeType','in':'query','required':false,'type':'string','enum':['MINUTE','HOUR','DAY']}],
        },
        [PushCollectStatController.pageByCriteria.method] : {
            summary: '按条件分页查询, 用于折线图,柱状图',
            method: 'get',
            url: (payload) => `/api/collect-stats/page-query`,
            parameters: [{'name':'appId','in':'query','required':false,'type':'string'},{'name':'clientCode','in':'query','required':false,'type':'string'},{'name':'dateBegin','in':'query','required':false,'type':'string','format':'date-time'},{'name':'dateEnd','in':'query','required':false,'type':'string','format':'date-time'},{'name':'extFlag','in':'query','required':false,'type':'integer','format':'int32'},{'name':'pageNum','in':'query','description':'第几页，从0开始','required':true,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','description':'单页条数','required':true,'type':'integer','format':'int32'},{'name':'pushType','in':'query','required':false,'type':'string','enum':['SIMPLE','TEMPLATE']},{'name':'timeType','in':'query','required':false,'type':'string','enum':['MINUTE','HOUR','DAY']}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
