//This file is automatically generated

// push-send-stat-controller

import { PushSendStatController } from '../controller';
export default {
    actions: {
        [PushSendStatController.findByCriteria.method] : {
            summary: '按条件查询, 用于折线图,柱状图',
            method: 'get',
            url: (payload) => `/api/send-stats/query`,
            parameters: [{'name':'appId','in':'query','required':false,'type':'string'},{'name':'channelType','in':'query','required':false,'type':'string','enum':['APNS','HUAWEI','XIAOMI','OPPO','VIVO','MEIZU']},{'name':'dateBegin','in':'query','required':false,'type':'string','format':'date-time'},{'name':'dateEnd','in':'query','required':false,'type':'string','format':'date-time'},{'name':'extFlag','in':'query','required':false,'type':'integer','format':'int32'},{'name':'platform','in':'query','required':false,'type':'string','enum':['IOS','ANDROID']},{'name':'status','in':'query','required':false,'type':'string','enum':['READY','EXPIRED','SENT','FAILED']},{'name':'timeType','in':'query','required':false,'type':'string','enum':['MINUTE','HOUR','DAY']}],
        },
        [PushSendStatController.getTodaySendCount.method] : {
            summary: '获取当日推送总数',
            method: 'get',
            url: (payload) => `/api/send-stats/${payload.appId}/today`,
            parameters: [{'name':'appId','in':'path','description':'appId','required':true,'type':'string'}],
        },
        [PushSendStatController.pageByCriteria.method] : {
            summary: '按条件分页查询, 用于折线图,柱状图',
            method: 'get',
            url: (payload) => `/api/send-stats/page-query`,
            parameters: [{'name':'appId','in':'query','required':false,'type':'string'},{'name':'channelType','in':'query','required':false,'type':'string','enum':['APNS','HUAWEI','XIAOMI','OPPO','VIVO','MEIZU']},{'name':'dateBegin','in':'query','required':false,'type':'string','format':'date-time'},{'name':'dateEnd','in':'query','required':false,'type':'string','format':'date-time'},{'name':'extFlag','in':'query','required':false,'type':'integer','format':'int32'},{'name':'pageNum','in':'query','description':'第几页，从0开始','required':true,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','description':'单页条数','required':true,'type':'integer','format':'int32'},{'name':'platform','in':'query','required':false,'type':'string','enum':['IOS','ANDROID']},{'name':'status','in':'query','required':false,'type':'string','enum':['READY','EXPIRED','SENT','FAILED']},{'name':'timeType','in':'query','required':false,'type':'string','enum':['MINUTE','HOUR','DAY']}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
