//This file is automatically generated

// push-collect-controller

import { PushCollectController } from '../controller';
export default {
    actions: {
        [PushCollectController.pushSimple.method] : {
            summary: '简单推送',
            method: 'post',
            url: (payload) => `/api/push-collect/simple`,
            parameters: [{'in':'body','name':'pushSimpleBO','description':'pushSimpleBO','required':true,'schema':{'originalRef':'简单推送���文体','$ref':'#/definitions/简单推送报文体'}}],
        },
        [PushCollectController.pushTemplate.method] : {
            summary: '模版推送',
            method: 'post',
            url: (payload) => `/api/push-collect/template`,
            parameters: [{'in':'body','name':'pushTemplateBO','description':'pushTemplateBO','required':true,'schema':{'originalRef':'模版推送报文体','$ref':'#/definitions/模版推送报文体'}}],
        },
        [PushCollectController.uploadTargetsArtifact.method] : {
            summary: '解析推送目标文件并去重, txt文件或json文件类型, UTF-8编码, txt为每行一个, json为数组',
            method: 'post',
            url: (payload) => `/api/push-collect/targets/artifact/upload`,
            parameters: [{'name':'artifact','in':'formData','description':'artifact','required':true,'type':'file'}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
