//This file is automatically generated

// push-message-controller

import { PushMessageController } from '../controller';
export default {
    actions: {
        [PushMessageController.create.method] : {
            summary: '新增',
            method: 'post',
            url: (payload) => `/api/messages`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'最终推送消息体','$ref':'#/definitions/最终推送消息体'}}],
        },
        [PushMessageController.deleteById.method] : {
            summary: '按主键删除',
            method: 'delete',
            url: (payload) => `/api/messages/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [PushMessageController.deleteByIds.method] : {
            summary: '按主键集合删除',
            method: 'put',
            url: (payload) => `/api/messages/bulk-delete`,
            parameters: [{'in':'body','name':'ids','description':'ids','required':true,'schema':{'type':'array','items':{'type':'string'}}}],
        },
        [PushMessageController.findByCriteria.method] : {
            summary: '按条件查询',
            method: 'get',
            url: (payload) => `/api/messages/query`,
            parameters: [{'name':'appId','in':'query','description':'应用id','required':false,'type':'string'},{'name':'channelType','in':'query','description':'通道类型:xiaomi,huawei,apns','required':false,'type':'string','enum':['APNS','HUAWEI','XIAOMI','OPPO','VIVO','MEIZU']},{'name':'messageType','in':'query','description':'消息类型: 透传,通知','required':false,'type':'string','enum':['NOTIFICATION','PASSTHROUGH','EMAIL','WEIXIN_TEMPLATE']},{'name':'priority','in':'query','description':'推送优先级','required':false,'type':'string','enum':['NORMAL','HIGH']},{'name':'pushEnv','in':'query','description':'推送环境,目前只针对ios的apns有效','required':false,'type':'string','enum':['DEV','PRO']},{'name':'status','in':'query','description':'消息状态','required':false,'type':'string','enum':['READY','EXPIRED','SENT','FAILED']},{'name':'taskId','in':'query','description':'任务id','required':false,'type':'string'},{'name':'token','in':'query','description':'由厂商sdk生成的设备推送token','required':false,'type':'string'},{'name':'traceId','in':'query','description':'发送到渠道后的消息追踪id','required':false,'type':'string'}],
        },
        [PushMessageController.findById.method] : {
            summary: '按主键查询',
            method: 'get',
            url: (payload) => `/api/messages/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [PushMessageController.pageByCriteria.method] : {
            summary: '按条件分页查询',
            method: 'get',
            url: (payload) => `/api/messages/page-query`,
            parameters: [{'name':'appId','in':'query','description':'应用id','required':false,'type':'string'},{'name':'channelType','in':'query','description':'通道类型:xiaomi,huawei,apns','required':false,'type':'string','enum':['APNS','HUAWEI','XIAOMI','OPPO','VIVO','MEIZU']},{'name':'messageType','in':'query','description':'消息类型: 透传,通知','required':false,'type':'string','enum':['NOTIFICATION','PASSTHROUGH','EMAIL','WEIXIN_TEMPLATE']},{'name':'pageNum','in':'query','description':'第几页，从0开始','required':true,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','description':'单页条数','required':true,'type':'integer','format':'int32'},{'name':'priority','in':'query','description':'推送优先级','required':false,'type':'string','enum':['NORMAL','HIGH']},{'name':'pushEnv','in':'query','description':'推送环境,目前只针对ios的apns有效','required':false,'type':'string','enum':['DEV','PRO']},{'name':'status','in':'query','description':'消息状态','required':false,'type':'string','enum':['READY','EXPIRED','SENT','FAILED']},{'name':'taskId','in':'query','description':'任务id','required':false,'type':'string'},{'name':'token','in':'query','description':'由厂商sdk生成的设备推送token','required':false,'type':'string'},{'name':'traceId','in':'query','description':'发送到渠道后的消息追踪id','required':false,'type':'string'}],
        },
        [PushMessageController.update.method] : {
            summary: '更新',
            method: 'put',
            url: (payload) => `/api/messages`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'最终推送消息体','$ref':'#/definitions/最终推送消息体'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
