//This file is automatically generated

// push-channel-controller

import { PushChannelController } from '../controller';
export default {
    actions: {
        [PushChannelController.create.method] : {
            summary: '新增',
            method: 'post',
            url: (payload) => `/api/channels`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'推送渠道配置','$ref':'#/definitions/推送渠道配置'}}],
        },
        [PushChannelController.createApnsChannel.method] : {
            summary: '创建ios apns推送通道',
            method: 'post',
            url: (payload) => `/api/channels/apns`,
            parameters: [{'in':'body','name':'apnsChannel','description':'apnsChannel','required':true,'schema':{'originalRef':'ApnsChannel','$ref':'#/definitions/ApnsChannel'}}],
        },
        [PushChannelController.createHuaweiChannel.method] : {
            summary: '创建android huawei推送通道',
            method: 'post',
            url: (payload) => `/api/channels/huawei`,
            parameters: [{'in':'body','name':'huaweiChannel','description':'huaweiChannel','required':true,'schema':{'originalRef':'HuaweiChannel','$ref':'#/definitions/HuaweiChannel'}}],
        },
        [PushChannelController.createMeizuChannel.method] : {
            summary: '创建android meizu推送通道',
            method: 'post',
            url: (payload) => `/api/channels/meizu`,
            parameters: [{'in':'body','name':'meizuChannel','description':'meizuChannel','required':true,'schema':{'originalRef':'MeizuChannel','$ref':'#/definitions/MeizuChannel'}}],
        },
        [PushChannelController.createOppoChannel.method] : {
            summary: '创建android oppo推送通道',
            method: 'post',
            url: (payload) => `/api/channels/oppo`,
            parameters: [{'in':'body','name':'oppoChannel','description':'oppoChannel','required':true,'schema':{'originalRef':'OppoChannel','$ref':'#/definitions/OppoChannel'}}],
        },
        [PushChannelController.createVivoChannel.method] : {
            summary: '创建android vivo推送通道',
            method: 'post',
            url: (payload) => `/api/channels/vivo`,
            parameters: [{'in':'body','name':'vivoChannel','description':'vivoChannel','required':true,'schema':{'originalRef':'VivoChannel','$ref':'#/definitions/VivoChannel'}}],
        },
        [PushChannelController.createXiaomiChannel.method] : {
            summary: '创建android xiaom推送通道',
            method: 'post',
            url: (payload) => `/api/channels/xiaomi`,
            parameters: [{'in':'body','name':'xiaomiChannel','description':'xiaomiChannel','required':true,'schema':{'originalRef':'XiaomiChannel','$ref':'#/definitions/XiaomiChannel'}}],
        },
        [PushChannelController.deleteById.method] : {
            summary: '按主键删除',
            method: 'delete',
            url: (payload) => `/api/channels/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [PushChannelController.deleteByIds.method] : {
            summary: '按主键集合删除',
            method: 'put',
            url: (payload) => `/api/channels/bulk-delete`,
            parameters: [{'in':'body','name':'ids','description':'ids','required':true,'schema':{'type':'array','items':{'type':'string'}}}],
        },
        [PushChannelController.findApnsChannelByCriteria.method] : {
            summary: '按条件获取apns通道',
            method: 'get',
            url: (payload) => `/api/channels/apns/query`,
            parameters: [{'name':'appId','in':'query','required':false,'type':'string'},{'name':'channelType','in':'query','required':false,'type':'string','enum':['APNS','HUAWEI','XIAOMI','OPPO','VIVO','MEIZU']},{'name':'enabled','in':'query','required':false,'type':'boolean'},{'name':'id','in':'query','description':'id','required':false,'type':'string'},{'name':'tenantId','in':'query','description':'租户id','required':false,'type':'string'},{'name':'usingEnabled','in':'query','required':false,'type':'boolean'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'}],
        },
        [PushChannelController.findById.method] : {
            summary: '按主键查询',
            method: 'get',
            url: (payload) => `/api/channels/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [PushChannelController.findHuaweiChannelByCriteria.method] : {
            summary: '按条件获取huawei通道',
            method: 'get',
            url: (payload) => `/api/channels/huawei/query`,
            parameters: [{'name':'appId','in':'query','required':false,'type':'string'},{'name':'channelType','in':'query','required':false,'type':'string','enum':['APNS','HUAWEI','XIAOMI','OPPO','VIVO','MEIZU']},{'name':'enabled','in':'query','required':false,'type':'boolean'},{'name':'id','in':'query','description':'id','required':false,'type':'string'},{'name':'tenantId','in':'query','description':'租户id','required':false,'type':'string'},{'name':'usingEnabled','in':'query','required':false,'type':'boolean'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'}],
        },
        [PushChannelController.findMeizuChannelByCriteria.method] : {
            summary: '按条件获取meizu通道',
            method: 'get',
            url: (payload) => `/api/channels/meizu/query`,
            parameters: [{'name':'appId','in':'query','required':false,'type':'string'},{'name':'channelType','in':'query','required':false,'type':'string','enum':['APNS','HUAWEI','XIAOMI','OPPO','VIVO','MEIZU']},{'name':'enabled','in':'query','required':false,'type':'boolean'},{'name':'id','in':'query','description':'id','required':false,'type':'string'},{'name':'tenantId','in':'query','description':'租户id','required':false,'type':'string'},{'name':'usingEnabled','in':'query','required':false,'type':'boolean'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'}],
        },
        [PushChannelController.findOppoChannelByCriteria.method] : {
            summary: '按条件获取oppo通道',
            method: 'get',
            url: (payload) => `/api/channels/oppo/query`,
            parameters: [{'name':'appId','in':'query','required':false,'type':'string'},{'name':'channelType','in':'query','required':false,'type':'string','enum':['APNS','HUAWEI','XIAOMI','OPPO','VIVO','MEIZU']},{'name':'enabled','in':'query','required':false,'type':'boolean'},{'name':'id','in':'query','description':'id','required':false,'type':'string'},{'name':'tenantId','in':'query','description':'租户id','required':false,'type':'string'},{'name':'usingEnabled','in':'query','required':false,'type':'boolean'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'}],
        },
        [PushChannelController.findVivoChannelByCriteria.method] : {
            summary: '按条件获取vivo通道',
            method: 'get',
            url: (payload) => `/api/channels/vivo/query`,
            parameters: [{'name':'appId','in':'query','required':false,'type':'string'},{'name':'channelType','in':'query','required':false,'type':'string','enum':['APNS','HUAWEI','XIAOMI','OPPO','VIVO','MEIZU']},{'name':'enabled','in':'query','required':false,'type':'boolean'},{'name':'id','in':'query','description':'id','required':false,'type':'string'},{'name':'tenantId','in':'query','description':'租户id','required':false,'type':'string'},{'name':'usingEnabled','in':'query','required':false,'type':'boolean'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'}],
        },
        [PushChannelController.findXiaomiChannelByCriteria.method] : {
            summary: '按条件获取xiaomi通道',
            method: 'get',
            url: (payload) => `/api/channels/xiaomi/query`,
            parameters: [{'name':'appId','in':'query','required':false,'type':'string'},{'name':'channelType','in':'query','required':false,'type':'string','enum':['APNS','HUAWEI','XIAOMI','OPPO','VIVO','MEIZU']},{'name':'enabled','in':'query','required':false,'type':'boolean'},{'name':'id','in':'query','description':'id','required':false,'type':'string'},{'name':'tenantId','in':'query','description':'租户id','required':false,'type':'string'},{'name':'usingEnabled','in':'query','required':false,'type':'boolean'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'}],
        },
        [PushChannelController.refreshPushChannel.method] : {
            summary: '刷新通道配置',
            method: 'get',
            url: (payload) => `/api/channels/refresh/${payload.id}`,
            parameters: [{'name':'force','in':'query','description':'force','required':false,'type':'boolean','default':true},{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [PushChannelController.update.method] : {
            summary: '更新',
            method: 'put',
            url: (payload) => `/api/channels`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'推送渠道配置','$ref':'#/definitions/推送渠道配置'}}],
        },
        [PushChannelController.updateApnsChannel.method] : {
            summary: '更新ios apns推送通道',
            method: 'put',
            url: (payload) => `/api/channels/apns`,
            parameters: [{'in':'body','name':'apnsChannelConfig','description':'apnsChannelConfig','required':true,'schema':{'originalRef':'ApnsChannel','$ref':'#/definitions/ApnsChannel'}}],
        },
        [PushChannelController.updateHuaweiChannel.method] : {
            summary: '更新android huawei推送通道',
            method: 'put',
            url: (payload) => `/api/channels/huawei`,
            parameters: [{'in':'body','name':'huaweiChannel','description':'huaweiChannel','required':true,'schema':{'originalRef':'HuaweiChannel','$ref':'#/definitions/HuaweiChannel'}}],
        },
        [PushChannelController.updateMeizuChannel.method] : {
            summary: '更新android meizu推送通道',
            method: 'put',
            url: (payload) => `/api/channels/meizu`,
            parameters: [{'in':'body','name':'meizuChannel','description':'meizuChannel','required':true,'schema':{'originalRef':'MeizuChannel','$ref':'#/definitions/MeizuChannel'}}],
        },
        [PushChannelController.updateOppoChannel.method] : {
            summary: '更新android oppo推送通道',
            method: 'put',
            url: (payload) => `/api/channels/oppo`,
            parameters: [{'in':'body','name':'oppoChannel','description':'oppoChannel','required':true,'schema':{'originalRef':'OppoChannel','$ref':'#/definitions/OppoChannel'}}],
        },
        [PushChannelController.updateVivoChannel.method] : {
            summary: '更新android vivo推送通道',
            method: 'put',
            url: (payload) => `/api/channels/vivo`,
            parameters: [{'in':'body','name':'vivoChannel','description':'vivoChannel','required':true,'schema':{'originalRef':'VivoChannel','$ref':'#/definitions/VivoChannel'}}],
        },
        [PushChannelController.updateXiaomiChannel.method] : {
            summary: '更新android xiaom推送通道',
            method: 'put',
            url: (payload) => `/api/channels/xiaomi`,
            parameters: [{'in':'body','name':'xiaomiChannel','description':'xiaomiChannel','required':true,'schema':{'originalRef':'XiaomiChannel','$ref':'#/definitions/XiaomiChannel'}}],
        },
        [PushChannelController.uploadApnsCert.method] : {
            summary: '上传apns证书',
            method: 'post',
            url: (payload) => `/api/channels/apns/upload/cert`,
            parameters: [{'name':'cert','in':'formData','description':'cert','required':true,'type':'file'}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
