//This file is automatically generated

// res-group-controller

import { ResGroupController } from '../controller';
export default {
    actions: {
        [ResGroupController.create.method] : {
            summary: '新增',
            method: 'post',
            url: (payload) => `/api/resource-groups`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'ResGroup','$ref':'#/definitions/ResGroup'}}],
        },
        [ResGroupController.deleteByIds.method] : {
            summary: '按主键集合(以&#x27;,&#x27;分割)删除',
            method: 'delete',
            url: (payload) => `/api/resource-groups/${payload.ids}`,
            parameters: [{'name':'ids','in':'path','description':'ids','required':true,'type':'string'}],
        },
        [ResGroupController.findByCriteria.method] : {
            summary: '按条件查询',
            method: 'get',
            url: (payload) => `/api/resource-groups/search`,
            parameters: [{'name':'code','in':'query','description':'编码','required':false,'type':'string'},{'name':'id','in':'query','description':'Id','required':false,'type':'string'},{'name':'listRoot','in':'query','description':'是否只查询顶层数据','required':false,'type':'boolean'},{'name':'loadChildren','in':'query','description':'是否加载子节点','required':false,'type':'boolean'},{'name':'loadChildrenLevel','in':'query','description':'从当前层开始，需要加载子节点的层级','required':false,'type':'integer','format':'int32'},{'name':'loadOthers','in':'query','description':'是否加载节点的其它资源','required':false,'type':'boolean'},{'name':'name','in':'query','description':'名称','required':false,'type':'string'},{'name':'parentId','in':'query','description':'父对象的id','required':false,'type':'string'},{'name':'type','in':'query','required':false,'type':'string'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'}],
        },
        [ResGroupController.findById.method] : {
            summary: '按主键查询',
            method: 'get',
            url: (payload) => `/api/resource-groups/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'},{'name':'loadChildren','in':'query','description':'loadChildren','required':false,'type':'boolean'},{'name':'loadLevel','in':'query','description':'loadLevel','required':false,'type':'integer','default':1,'format':'int32'},{'name':'loadOthers','in':'query','description':'loadOthers','required':false,'type':'boolean'}],
        },
        [ResGroupController.findSubFunctionByCriteria.method] : {
            summary: '查询某资源组下的功能',
            method: 'get',
            url: (payload) => `/api/resource-groups/${payload.groupId}/functions`,
            parameters: [{'name':'code','in':'query','description':'编码','required':false,'type':'string'},{'name':'groupId','in':'path','description':'groupId','required':true,'type':'string'},{'name':'groupId','in':'query','required':false,'type':'string'},{'name':'id','in':'query','description':'Id','required':false,'type':'string'},{'name':'name','in':'query','description':'名称','required':false,'type':'string'},{'name':'type','in':'query','required':false,'type':'string'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'}],
        },
        [ResGroupController.findSubMenuByCriteria.method] : {
            summary: '查询某资源组下的菜单',
            method: 'get',
            url: (payload) => `/api/resource-groups/${payload.groupId}/menus`,
            parameters: [{'name':'code','in':'query','description':'编码','required':false,'type':'string'},{'name':'groupId','in':'path','description':'groupId','required':true,'type':'string'},{'name':'groupId','in':'query','required':false,'type':'string'},{'name':'id','in':'query','description':'Id','required':false,'type':'string'},{'name':'listRoot','in':'query','description':'是否只查询顶层数据','required':false,'type':'boolean'},{'name':'loadChildren','in':'query','description':'是否加载子节点','required':false,'type':'boolean'},{'name':'loadChildrenLevel','in':'query','description':'从当前层开始，需要加载子节点的层级','required':false,'type':'integer','format':'int32'},{'name':'loadOthers','in':'query','description':'是否加载节点的其它资源','required':false,'type':'boolean'},{'name':'name','in':'query','description':'名称','required':false,'type':'string'},{'name':'parentId','in':'query','description':'父对象的id','required':false,'type':'string'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'}],
        },
        [ResGroupController.pagingByCriteria.method] : {
            summary: '分页查询',
            method: 'get',
            url: (payload) => `/api/resource-groups/page-search`,
            parameters: [{'name':'code','in':'query','description':'编码','required':false,'type':'string'},{'name':'id','in':'query','description':'Id','required':false,'type':'string'},{'name':'listRoot','in':'query','description':'是否只查询顶层数据','required':false,'type':'boolean'},{'name':'loadChildren','in':'query','description':'是否加载子节点','required':false,'type':'boolean'},{'name':'loadChildrenLevel','in':'query','description':'从当前层开始，需要加载子节点的层级','required':false,'type':'integer','format':'int32'},{'name':'loadOthers','in':'query','description':'是否加载节点的其它资源','required':false,'type':'boolean'},{'name':'name','in':'query','description':'名称','required':false,'type':'string'},{'name':'pageNum','in':'query','required':false,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','required':false,'type':'integer','format':'int32'},{'name':'parentId','in':'query','description':'父对象的id','required':false,'type':'string'},{'name':'type','in':'query','required':false,'type':'string'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'}],
        },
        [ResGroupController.update.method] : {
            summary: '更新',
            method: 'put',
            url: (payload) => `/api/resource-groups`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'ResGroup','$ref':'#/definitions/ResGroup'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
