//This file is automatically generated

// role-tpl-group-controller

import { RoleTplGroupController } from '../controller';
export default {
    actions: {
        [RoleTplGroupController.create.method] : {
            summary: '新增',
            method: 'post',
            url: (payload) => `/api/role-template-groups`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'RoleTplGroup','$ref':'#/definitions/RoleTplGroup'}}],
        },
        [RoleTplGroupController.deleteByIds.method] : {
            summary: '按主键集合删除',
            method: 'put',
            url: (payload) => `/api/role-template-groups/bulk-delete`,
            parameters: [{'in':'body','name':'ids','description':'ids','required':true,'schema':{'type':'array','items':{'type':'string'}}}],
        },
        [RoleTplGroupController.findByCriteria.method] : {
            summary: '按条件查询',
            method: 'get',
            url: (payload) => `/api/role-template-groups/search`,
            parameters: [{'name':'id','in':'query','description':'Id','required':false,'type':'string'},{'name':'name','in':'query','description':'名称','required':false,'type':'string'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'}],
        },
        [RoleTplGroupController.findById.method] : {
            summary: '按主键查询',
            method: 'get',
            url: (payload) => `/api/role-template-groups/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [RoleTplGroupController.newRoleInstances.method] : {
            summary: '按条件查询',
            method: 'post',
            url: (payload) => `/api/role-template-groups/${payload.id}/new-role-instances`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'},{'name':'ownerId','in':'query','description':'ownerId','required':false,'type':'string'},{'name':'ownerType','in':'query','description':'ownerType','required':false,'type':'string'}],
        },
        [RoleTplGroupController.update.method] : {
            summary: '更新',
            method: 'put',
            url: (payload) => `/api/role-template-groups`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'RoleTplGroup','$ref':'#/definitions/RoleTplGroup'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
