//This file is automatically generated

// role-controller

import { RoleController } from '../controller';
export default {
    actions: {
        [RoleController.bindRoleToUsers.method] : {
            summary: '将角色绑定至用户(用户id以&#x27;,&#x27;分割)',
            method: 'put',
            url: (payload) => `/api/roles/${payload.id}/users/${payload.userIds}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'},{'name':'userIds','in':'path','description':'userIds','required':true,'type':'string'}],
        },
        [RoleController.create.method] : {
            summary: '新增',
            method: 'post',
            url: (payload) => `/api/roles`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'角色','$ref':'#/definitions/角色'}}],
        },
        [RoleController.deleteByIds.method] : {
            summary: '按主键集合删除',
            method: 'put',
            url: (payload) => `/api/roles/bulk-delete`,
            parameters: [{'in':'body','name':'ids','description':'ids','required':true,'schema':{'type':'array','items':{'type':'string'}}}],
        },
        [RoleController.findById.method] : {
            summary: '按主键查询',
            method: 'get',
            url: (payload) => `/api/roles/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [RoleController.getUsersByRoleId.method] : {
            summary: '分页查询拥有某角色的用户',
            method: 'get',
            url: (payload) => `/api/roles/${payload.id}/users`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'},{'name':'name','in':'query','description':'name','required':false,'type':'string'},{'name':'pageNum','in':'query','required':false,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','required':false,'type':'integer','format':'int32'}],
        },
        [RoleController.handleRoleTplResource.method] : {
            summary: '修改角色资源',
            method: 'put',
            url: (payload) => `/api/roles/${payload.id}/resources`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'},{'in':'body','name':'operatableResources','description':'operatableResources','required':true,'schema':{'type':'array','items':{'originalRef':'带操作的资源','$ref':'#/definitions/带操作的资源'}}}],
        },
        [RoleController.loadWholeResources.method] : {
            summary: '查询角色对应的全部资源',
            method: 'get',
            url: (payload) => `/api/roles/${payload.id}/resources`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [RoleController.pagingByCriteria.method] : {
            summary: '分页查询所有角色',
            method: 'get',
            url: (payload) => `/api/roles/page-search`,
            parameters: [{'name':'code','in':'query','description':'编码','required':false,'type':'string'},{'name':'id','in':'query','description':'Id','required':false,'type':'string'},{'name':'listPlatformRoles','in':'query','required':false,'type':'boolean'},{'name':'name','in':'query','description':'名称','required':false,'type':'string'},{'name':'ownerId','in':'query','required':false,'type':'string'},{'name':'ownerType','in':'query','required':false,'type':'string'},{'name':'pageNum','in':'query','required':false,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','required':false,'type':'integer','format':'int32'},{'name':'roleTplId','in':'query','required':false,'type':'string'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'}],
        },
        [RoleController.unbindRoleToUsers.method] : {
            summary: '将角色绑定的用户解绑(用户id以&#x27;,&#x27;分割)',
            method: 'delete',
            url: (payload) => `/api/roles/${payload.id}/users/${payload.userIds}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'},{'name':'userIds','in':'path','description':'userIds','required':true,'type':'string'}],
        },
        [RoleController.update.method] : {
            summary: '更新',
            method: 'put',
            url: (payload) => `/api/roles`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'角色','$ref':'#/definitions/角色'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
