//This file is automatically generated

// role-tpl-controller

import { RoleTplController } from '../controller';
export default {
    actions: {
        [RoleTplController.create.method] : {
            summary: '新增',
            method: 'post',
            url: (payload) => `/api/role-templates`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'RoleTpl','$ref':'#/definitions/RoleTpl'}}],
        },
        [RoleTplController.deleteByIds.method] : {
            summary: '按主键集合删除',
            method: 'put',
            url: (payload) => `/api/role-templates/bulk-delete`,
            parameters: [{'in':'body','name':'ids','description':'ids','required':true,'schema':{'type':'array','items':{'type':'string'}}}],
        },
        [RoleTplController.findByCriteria.method] : {
            summary: '按条件查询',
            method: 'get',
            url: (payload) => `/api/role-templates/search`,
            parameters: [{'name':'authTplId','in':'query','required':false,'type':'string'},{'name':'groupId','in':'query','required':false,'type':'string'},{'name':'id','in':'query','description':'Id','required':false,'type':'string'},{'name':'name','in':'query','description':'名称','required':false,'type':'string'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'}],
        },
        [RoleTplController.findById.method] : {
            summary: '按主键查询',
            method: 'get',
            url: (payload) => `/api/role-templates/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [RoleTplController.handleRoleTplResource.method] : {
            summary: '修改角色模板资源',
            method: 'put',
            url: (payload) => `/api/role-templates/${payload.id}/resources`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'},{'in':'body','name':'operatableResources','description':'operatableResources','required':true,'schema':{'type':'array','items':{'originalRef':'带操作的资源','$ref':'#/definitions/带操作的资源'}}}],
        },
        [RoleTplController.loadWholeResources.method] : {
            summary: '查询角色模板对应的资源树',
            method: 'get',
            url: (payload) => `/api/role-templates/${payload.id}/resources`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [RoleTplController.pageRoleByTemplateId.method] : {
            summary: '查询使用此模板创建的角色',
            method: 'get',
            url: (payload) => `/api/role-templates/${payload.id}/roles`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'},{'name':'pageNum','in':'query','required':false,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','required':false,'type':'integer','format':'int32'},{'name':'roleName','in':'query','description':'roleName','required':false,'type':'string'}],
        },
        [RoleTplController.update.method] : {
            summary: '更新',
            method: 'put',
            url: (payload) => `/api/role-templates`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'RoleTpl','$ref':'#/definitions/RoleTpl'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
