//This file is automatically generated

// statistic-crash-stat-controller

import { StatisticCrashStatController } from '../controller';
export default {
    actions: {
        [StatisticCrashStatController.findByCriteria.method] : {
            summary: '查询统计信息，用于统计折线图',
            method: 'get',
            url: (payload) => `/api/crash-stats/query`,
            parameters: [{'name':'appId','in':'query','description':'应用标识','required':true,'type':'string'},{'name':'appVersionId','in':'query','description':'应用版本','required':false,'type':'string'},{'name':'buildNo','in':'query','description':'构建版本','required':false,'type':'string'},{'name':'catalog','in':'query','description':'Crash异常类型','required':false,'type':'string'},{'name':'dateBegin','in':'query','description':'开始时间','required':false,'type':'string','format':'date-time'},{'name':'dateEnd','in':'query','description':'结束时间','required':false,'type':'string','format':'date-time'},{'name':'extFlag','in':'query','description':'数据标识，1代表已处理，0代表未处理，外部查询需要传1','required':true,'type':'integer','format':'int32'},{'name':'osVersion','in':'query','description':'系统版本','required':false,'type':'string'},{'name':'platform','in':'query','description':'系统类型','required':false,'type':'string'},{'name':'timeType','in':'query','description':'查询时间类型','required':true,'type':'string','enum':['MINUTE','HOUR','DAY']}],
        },
        [StatisticCrashStatController.getAppTodayCrashCount.method] : {
            summary: '查询某个App今天的crash次数',
            method: 'get',
            url: (payload) => `/api/crash-stats/crash-count-today/${payload.appId}`,
            parameters: [{'name':'appId','in':'path','description':'appId','required':true,'type':'string'}],
        },
        [StatisticCrashStatController.getAppTotalCrashCount.method] : {
            summary: '查询某个App总的crash次数',
            method: 'get',
            url: (payload) => `/api/crash-stats/crash-count-all/${payload.appId}`,
            parameters: [{'name':'appId','in':'path','description':'appId','required':true,'type':'string'}],
        },
        [StatisticCrashStatController.getCrashDetails.method] : {
            summary: '查询详细的crash异常，传timeType是为了更好的锁定ES检索范围',
            method: 'get',
            url: (payload) => `/api/crash-stats/query-crash-log`,
            parameters: [{'name':'appId','in':'query','description':'应用标识','required':true,'type':'string'},{'name':'appVersionId','in':'query','description':'应用版本','required':true,'type':'string'},{'name':'buildNo','in':'query','description':'构建版本','required':true,'type':'string'},{'name':'catalog','in':'query','description':'Crash异常类型','required':true,'type':'string'},{'name':'osVersion','in':'query','description':'系统版本','required':true,'type':'string'},{'name':'platform','in':'query','description':'系统类型','required':true,'type':'string'},{'name':'timePoint','in':'query','description':'crash时间点，使用yyyy-MM-dd HH:mm格式','required':true,'type':'string','format':'date-time'},{'name':'timeType','in':'query','description':'查询时间类型','required':true,'type':'string','enum':['MINUTE','HOUR','DAY']}],
        },
        [StatisticCrashStatController.pagingByMinuteCriteria.method] : {
            summary: '分页查询统计信息，用于定位具体信息',
            method: 'get',
            url: (payload) => `/api/crash-stats/page-query`,
            parameters: [{'name':'appId','in':'query','description':'应用标识','required':true,'type':'string'},{'name':'appVersionId','in':'query','description':'应用版本','required':false,'type':'string'},{'name':'buildNo','in':'query','description':'构建版本','required':false,'type':'string'},{'name':'catalog','in':'query','description':'Crash异常类型','required':false,'type':'string'},{'name':'dateBegin','in':'query','description':'开始时间','required':false,'type':'string','format':'date-time'},{'name':'dateEnd','in':'query','description':'结束时间','required':false,'type':'string','format':'date-time'},{'name':'extFlag','in':'query','description':'数据标识，1代表已处理，0代表未处理，外部查询需要传1','required':true,'type':'integer','format':'int32'},{'name':'osVersion','in':'query','description':'系统版本','required':false,'type':'string'},{'name':'pageNum','in':'query','description':'第几页，从0开始','required':true,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','description':'单页条数','required':true,'type':'integer','format':'int32'},{'name':'platform','in':'query','description':'系统类型','required':false,'type':'string'},{'name':'timeType','in':'query','description':'查询时间类型','required':true,'type':'string','enum':['MINUTE','HOUR','DAY']}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
