//This file is automatically generated

// statistic-org-compare-controller

import { StatisticOrgCompareController } from '../controller';
export default {
    actions: {
        [StatisticOrgCompareController.findByCriteria.method] : {
            summary: '查询部门对比统计信息',
            method: 'get',
            url: (payload) => `/api/org-compare/query`,
            parameters: [{'name':'appId','in':'query','description':'应用标识','required':true,'type':'string'},{'name':'appVersionId','in':'query','description':'应用版本','required':false,'type':'string'},{'name':'dateBegin','in':'query','description':'开始时间','required':false,'type':'string','format':'date-time'},{'name':'dateEnd','in':'query','description':'结束时间','required':false,'type':'string','format':'date-time'},{'name':'extFlag','in':'query','description':'数据标识，1代表已处理，0代表未处理，外部查询需要传1','required':true,'type':'integer','format':'int32'},{'name':'orgId','in':'query','description':'机构标识，目前不用传，为后续下攥预留','required':false,'type':'string'},{'name':'orgLevel','in':'query','description':'机构级别','required':true,'type':'integer','format':'int32'},{'name':'timeType','in':'query','description':'查询时间类型','required':true,'type':'string','enum':['MINUTE','HOUR','DAY']}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
