//This file is automatically generated

// statistic-platform-controller

import { StatisticPlatformController } from '../controller';
export default {
    actions: {
        [StatisticPlatformController.queryPlatformTypeList.method] : {
            summary: '查询收集的系统类型列表',
            method: 'get',
            url: (payload) => `/api/platform/type/query`,
            parameters: [],
        },
        [StatisticPlatformController.queryPlatformVersionList.method] : {
            summary: '查询收集的系统版本列表',
            method: 'get',
            url: (payload) => `/api/platform/os/query/${payload.appId}/${payload.platform}`,
            parameters: [{'name':'appId','in':'path','description':'appId','required':true,'type':'string'},{'name':'platform','in':'path','description':'platform','required':true,'type':'string'}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
