//This file is automatically generated

// tools-controller

import { ToolsController } from '../controller';
export default {
    actions: {
        [ToolsController.scanFunctions.method] : {
            summary: '通过代码扫描, 获取应用的功能定义',
            method: 'get',
            url: (payload) => `/api/tools/scan-functions`,
            parameters: [{'name':'basePackage','in':'query','description':'需要额外扫描的包名. 扫描时, 默认会先扫描所有的ComponentScan注解, 获取所有的basePackage. 如果应用启动类没有配置此注解, 则可以通过此参数添加需要扫描的包','required':false,'type':'string','allowEmptyValue':false},{'name':'endpoint','in':'query','description':'应用地址, 格式为: http://ip:端口/contextPath','required':false,'type':'string','allowEmptyValue':false}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
