//This file is automatically generated

// workgroup-controller

import { WorkgroupController } from '../controller';
export default {
    actions: {
        [WorkgroupController.addWorkgroupEmployees.method] : {
            summary: '往工作组下添加员工',
            method: 'put',
            url: (payload) => `/api/workgroups/${payload.id}/employees/${payload.employeeIds}`,
            parameters: [{'name':'employeeIds','in':'path','description':'employeeIds','required':true,'type':'string'},{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [WorkgroupController.create.method] : {
            summary: '新增',
            method: 'post',
            url: (payload) => `/api/workgroups`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'工作组','$ref':'#/definitions/工作组'}}],
        },
        [WorkgroupController.deleteByIds.method] : {
            summary: '按主键集合(以&#x27;,&#x27;分割)删除',
            method: 'delete',
            url: (payload) => `/api/workgroups/${payload.ids}`,
            parameters: [{'name':'ids','in':'path','description':'ids','required':true,'type':'string'}],
        },
        [WorkgroupController.findById.method] : {
            summary: '按主键查询',
            method: 'get',
            url: (payload) => `/api/workgroups/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'},{'name':'loadChildren','in':'query','description':'loadChildren','required':false,'type':'boolean'},{'name':'loadLevel','in':'query','description':'loadLevel','required':false,'type':'integer','default':1,'format':'int32'},{'name':'loadOthers','in':'query','description':'loadOthers','required':false,'type':'boolean'}],
        },
        [WorkgroupController.pagingByCriteria.method] : {
            summary: '分页查询',
            method: 'get',
            url: (payload) => `/api/workgroups/page-search`,
            parameters: [{'name':'code','in':'query','description':'编码','required':false,'type':'string'},{'name':'id','in':'query','description':'Id','required':false,'type':'string'},{'name':'listRoot','in':'query','description':'是否只查询顶层数据','required':false,'type':'boolean'},{'name':'loadChildren','in':'query','description':'是否加载子节点','required':false,'type':'boolean'},{'name':'loadChildrenLevel','in':'query','description':'从当前层开始，需要加载子节点的层级','required':false,'type':'integer','format':'int32'},{'name':'loadOthers','in':'query','description':'是否加载节点的其它资源','required':false,'type':'boolean'},{'name':'name','in':'query','description':'名称','required':false,'type':'string'},{'name':'organizationId','in':'query','required':false,'type':'string'},{'name':'pageNum','in':'query','required':false,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','required':false,'type':'integer','format':'int32'},{'name':'parentId','in':'query','description':'父对象的id','required':false,'type':'string'},{'name':'status','in':'query','required':false,'type':'string'},{'name':'type','in':'query','required':false,'type':'string'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'}],
        },
        [WorkgroupController.querySubEmployees.method] : {
            summary: '查询工作组下的员���',
            method: 'get',
            url: (payload) => `/api/workgroups/${payload.id}/employees`,
            parameters: [{'name':'employeeName','in':'query','description':'employeeName','required':false,'type':'string'},{'name':'id','in':'path','description':'id','required':true,'type':'string'},{'name':'pageNum','in':'query','required':false,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','required':false,'type':'integer','format':'int32'}],
        },
        [WorkgroupController.removeWorkgroupEmployees.method] : {
            summary: '从工作组下移除员工',
            method: 'delete',
            url: (payload) => `/api/workgroups/${payload.id}/employees/${payload.employeeIds}`,
            parameters: [{'name':'employeeIds','in':'path','description':'employeeIds','required':true,'type':'string'},{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [WorkgroupController.update.method] : {
            summary: '更新',
            method: 'put',
            url: (payload) => `/api/workgroups`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'originalRef':'工作组','$ref':'#/definitions/工作组'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
