//This file is automatically generated

// {{tags}}

import { {{model}} } from '../controller';
export default {
    actions: {
    {{#list}}
        [{{this.model}}.{{this.action}}.method] : {
            summary: '{{this.summary}}',
            method: '{{this.method}}',
            url: (payload) => `{{this.url}}`,
            parameters: {{this.parameters}},
        },
    {{/list}}
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
